const P = (x, y) => ({ x, y })

const edge = (source, target, sourceHandle = null) => ({
  id: `edge-${source}-${sourceHandle || 'default'}-${target}-default`,
  source,
  target,
  sourceHandle,
  targetHandle: null,
  animated: true,
})

const TEMPLATES = [
  {
    id: 'ecommerce-sales',
    name: 'E-Commerce Sales Assistant',
    industry: 'E-Commerce',
    description: 'Qualify intent, show products, send payment, and hand off support requests.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'Customer sends a WhatsApp message' } },
      { id: 'cond-buy', type: 'condition', position: P(300, 160), data: { matchType: 'contains', keyword: 'buy' } },
      { id: 'cat-1', type: 'catalog', position: P(120, 320), data: { productIds: [], message: 'Here are our best-selling products:' } },
      { id: 'pay-1', type: 'payment', position: P(120, 480), data: { message: 'Use this link to complete your order.', label: 'Pay now', linkTemplate: 'https://example.com/checkout?phone={{phone}}', amount: '', currency: 'INR ' } },
      { id: 'cond-help', type: 'condition', position: P(500, 320), data: { matchType: 'contains', keyword: 'agent' } },
      { id: 'send-help', type: 'send', position: P(410, 480), data: { sendMode: 'text', message: 'I am connecting you to a team member now.', footer: '', title: '', buttons: [], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'handoff-1', type: 'handoff', position: P(410, 630), data: { reason: 'support requested', note: 'Customer asked for help during shopping.', assignee: '' } },
      { id: 'ai-1', type: 'ai', position: P(620, 480), data: { provider: 'openai', systemPrompt: 'You are an e-commerce assistant. Ask what product the customer wants, answer briefly, and invite them to type buy to see products or agent for help.' } },
    ],
    edges: [
      edge('trigger-1', 'cond-buy'),
      edge('cond-buy', 'cat-1', 'true'),
      edge('cat-1', 'pay-1'),
      edge('cond-buy', 'cond-help', 'false'),
      edge('cond-help', 'send-help', 'true'),
      edge('send-help', 'handoff-1'),
      edge('cond-help', 'ai-1', 'false'),
    ],
  },
  {
    id: 'ecommerce-menu-router',
    name: 'E-Commerce Menu Router',
    industry: 'E-Commerce',
    description: 'Send a shopping menu first, then route product, order, and support choices on the next reply.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(360, 20), data: { label: 'Customer sends a message or taps a menu option' } },
      { id: 'cond-browse', type: 'condition', position: P(360, 140), data: { matchType: 'equals', keyword: 'browse_products' } },
      { id: 'cat-1', type: 'catalog', position: P(120, 300), data: { productIds: [], message: 'Here are the products you can order today:' } },
      { id: 'send-checkout', type: 'send', position: P(120, 470), data: { sendMode: 'buttons', message: 'If you like any item, tap checkout below or reply with the product name.', footer: 'Fast checkout', title: '', buttons: [{ type: 'cta_url', label: 'Open checkout', url: 'https://example.com/checkout?phone={{phone}}' }, { type: 'quick_reply', label: 'Talk to agent', id: 'talk_agent' }], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'cond-order', type: 'condition', position: P(360, 300), data: { matchType: 'equals', keyword: 'track_order' } },
      { id: 'send-order', type: 'send', position: P(360, 470), data: { sendMode: 'buttons', message: 'Share your order ID and we will help you track it, or open the tracking page below.', footer: '', title: '', buttons: [{ type: 'cta_url', label: 'Track order', url: 'https://example.com/orders/track?phone={{phone}}' }, { type: 'quick_reply', label: 'Talk to agent', id: 'talk_agent' }], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'cond-agent', type: 'condition', position: P(620, 470), data: { matchType: 'contains', keyword: 'agent' } },
      { id: 'send-agent', type: 'send', position: P(620, 630), data: { sendMode: 'text', message: 'Connecting you to our support team now.', footer: '', title: '', buttons: [], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'handoff-1', type: 'handoff', position: P(620, 790), data: { reason: 'shopping support', note: 'Customer requested help from the shopping menu.', assignee: '' } },
      { id: 'send-menu', type: 'send', position: P(820, 630), data: { sendMode: 'list', message: 'Welcome to our store. Choose what you want to do next:', footer: 'Select one option', title: '', buttons: [], list: { title: 'Shopping menu', buttonText: 'Open menu', sections: [{ title: 'Store options', rows: [{ title: 'Browse products', description: 'See our catalog and current offers', rowId: 'browse_products' }, { title: 'Track order', description: 'Check an existing order status', rowId: 'track_order' }, { title: 'Talk to agent', description: 'Get help from our team', rowId: 'talk_agent' }] }] }, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
    ],
    edges: [
      edge('trigger-1', 'cond-browse'),
      edge('cond-browse', 'cat-1', 'true'),
      edge('cat-1', 'send-checkout'),
      edge('cond-browse', 'cond-order', 'false'),
      edge('cond-order', 'send-order', 'true'),
      edge('cond-order', 'cond-agent', 'false'),
      edge('cond-agent', 'send-agent', 'true'),
      edge('send-agent', 'handoff-1'),
      edge('cond-agent', 'send-menu', 'false'),
    ],
  },
  {
    id: 'real-estate-lead',
    name: 'Real Estate Lead Qualifier',
    industry: 'Real Estate',
    description: 'Qualify budget/location, show listings, and book a site visit.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'New property enquiry' } },
      { id: 'ai-1', type: 'ai', position: P(300, 160), data: { provider: 'openai', systemPrompt: 'You are a real estate assistant. Ask for budget, location, and property type one question at a time.' } },
      { id: 'set-1', type: 'set', position: P(300, 320), data: { field: 'leadStage', value: 'qualified' } },
      { id: 'cat-1', type: 'catalog', position: P(300, 470), data: { productIds: [], message: 'Here are matching properties:' } },
      { id: 'book-1', type: 'booking', position: P(300, 630), data: { service: 'site visit', daysAhead: 5, startHour: 10, endHour: 18, intervalMins: 60, reminderHours: 24, message: 'Choose a time for your site visit:' } },
    ],
    edges: [
      edge('trigger-1', 'ai-1'),
      edge('ai-1', 'set-1'),
      edge('set-1', 'cat-1'),
      edge('cat-1', 'book-1'),
    ],
  },
  {
    id: 'salon-booking',
    name: 'Salon Appointment Booking',
    industry: 'Salon & Wellness',
    description: 'Route booking requests to slots and other messages to an AI assistant.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'Customer message received' } },
      { id: 'cond-1', type: 'condition', position: P(300, 160), data: { matchType: 'contains', keyword: 'book' } },
      { id: 'book-1', type: 'booking', position: P(120, 320), data: { service: 'appointment', daysAhead: 4, startHour: 9, endHour: 19, intervalMins: 30, reminderHours: 24, message: 'Choose an appointment time:' } },
      { id: 'ai-1', type: 'ai', position: P(480, 320), data: { provider: 'openai', systemPrompt: 'You are a salon assistant. Answer service and price questions, then invite the customer to type book.' } },
    ],
    edges: [
      edge('trigger-1', 'cond-1'),
      edge('cond-1', 'book-1', 'true'),
      edge('cond-1', 'ai-1', 'false'),
    ],
  },
  {
    id: 'fee-reminder',
    name: 'Fee Reminder And Payment',
    industry: 'Education',
    description: 'Detect fee questions, send a payment link, and schedule a follow-up.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'Student or parent message' } },
      { id: 'cond-1', type: 'condition', position: P(300, 160), data: { matchType: 'contains', keyword: 'fee' } },
      { id: 'pay-1', type: 'payment', position: P(160, 320), data: { message: 'Here is your fee payment link.', label: 'Pay fees', linkTemplate: 'https://example.com/pay-fees?phone={{phone}}', currency: 'INR ' } },
      { id: 'schedule-1', type: 'schedule', position: P(160, 470), data: { seconds: 86400, message: 'Reminder: your fee payment is pending. Please complete it when possible.' } },
      { id: 'send-1', type: 'send', position: P(480, 320), data: { sendMode: 'text', message: 'Please type fee if you need payment details, or ask your question here.', footer: '', title: '', buttons: [], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
    ],
    edges: [
      edge('trigger-1', 'cond-1'),
      edge('cond-1', 'pay-1', 'true'),
      edge('pay-1', 'schedule-1'),
      edge('cond-1', 'send-1', 'false'),
    ],
  },
  {
    id: 'clinic-appointment-router',
    name: 'Clinic Appointment And FAQ',
    industry: 'Clinic / Healthcare',
    description: 'Book consultation slots, save the visit type, notify your clinic system, and hand sensitive questions to staff.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(360, 20), data: { label: 'Patient sends a WhatsApp message' } },
      { id: 'cond-book', type: 'condition', position: P(360, 160), data: { matchType: 'contains', keyword: 'appointment' } },
      { id: 'book-1', type: 'booking', position: P(120, 320), data: { service: 'consultation', daysAhead: 7, startHour: 9, endHour: 18, intervalMins: 30, reminderHours: 24, message: 'Choose a consultation slot:', confirmMessage: 'Your consultation is confirmed for {{slot}}. Reply agent if you need reception help.' } },
      { id: 'set-1', type: 'set', position: P(120, 480), data: { field: 'visitType', value: 'General consultation' } },
      { id: 'api-1', type: 'api', position: P(120, 640), data: { method: 'POST', url: 'https://example.com/api/appointments', headers: [{ key: 'Content-Type', value: 'application/json' }], bodyTemplate: '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "visitType": "{{visitType}}"\n}', saveAs: 'booking' } },
      { id: 'send-confirm', type: 'send', position: P(120, 800), data: { sendMode: 'text', message: 'Booked for {{slot}}. Please arrive 10 minutes early and carry any previous prescriptions.', footer: '', title: '', buttons: [], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'cond-agent', type: 'condition', position: P(540, 320), data: { matchType: 'contains', keyword: 'agent' } },
      { id: 'send-agent', type: 'send', position: P(540, 480), data: { sendMode: 'text', message: 'Connecting you to the clinic reception team now.', footer: '', title: '', buttons: [], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'handoff-1', type: 'handoff', position: P(540, 640), data: { reason: 'patient support', note: 'Patient requested human help for booking or a sensitive question.', assignee: '' } },
      { id: 'ai-1', type: 'ai', position: P(780, 480), data: { provider: 'openai', systemPrompt: 'You are a clinic WhatsApp assistant. Answer FAQs about timings, doctors, and visit preparation briefly. Invite patients to type appointment to book or agent for reception help with sensitive cases.' } },
    ],
    edges: [
      edge('trigger-1', 'cond-book'),
      edge('cond-book', 'book-1', 'true'),
      edge('book-1', 'set-1'),
      edge('set-1', 'api-1'),
      edge('api-1', 'send-confirm'),
      edge('cond-book', 'cond-agent', 'false'),
      edge('cond-agent', 'send-agent', 'true'),
      edge('send-agent', 'handoff-1'),
      edge('cond-agent', 'ai-1', 'false'),
    ],
  },
  {
    id: 'ai-smart-front-desk',
    name: 'Clinic Smart Front Desk',
    industry: 'Clinic / Healthcare',
    description: 'Let AI route each patient message to booking, intake, reminders, a staff handoff, or a fallback reply.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(360, 20), data: { label: 'Customer sends a WhatsApp message' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(360, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt: 'You route inbound WhatsApp messages for a clinic. Choose the pricing route for fee or package questions, the booking route for appointment requests, the menu route when the patient wants options or departments, the human route for complaints or explicit staff requests, and the fallback route for general FAQs.',
          confidenceThreshold: 0.55,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Fees and pricing', description: 'Patient is asking about consultation fees, packages, or cost.' },
            { id: 'route_2', label: 'Booking flow', description: 'Patient wants to book, reschedule, reserve, or pick a time slot.' },
            { id: 'route_3', label: 'Clinic options', description: 'Patient wants to browse departments, visit types, or available options before deciding.' },
            { id: 'route_4', label: 'Human support', description: 'Patient is upset, needs custom help, or asks for reception or a staff member.' },
            { id: 'fallback', label: 'FAQ fallback', description: 'General question or low-confidence case. Let AI answer normally.' },
          ],
        },
      },
      { id: 'send-pricing', type: 'send', position: P(60, 380), data: { sendMode: 'buttons', message: 'Here are the fastest ways to move forward:', footer: 'Choose one option', title: '', buttons: [{ type: 'cta_url', label: 'View fees', url: 'https://example.com/fees' }, { type: 'quick_reply', label: 'Request callback', id: 'book_call' }], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'book-1', type: 'booking', position: P(260, 380), data: { service: 'consultation', daysAhead: 5, startHour: 10, endHour: 18, intervalMins: 30, reminderHours: 24, message: 'Pick a time for your consultation:', confirmMessage: 'Your consultation is confirmed for {{slot}}.' } },
      { id: 'send-menu', type: 'send', position: P(470, 380), data: { sendMode: 'list', message: 'Choose what you want help with next:', footer: 'Select one option', title: '', buttons: [], list: { title: 'Quick menu', buttonText: 'Open options', sections: [{ title: 'Popular actions', rows: [{ title: 'See departments', description: 'Browse visit categories and specialties', rowId: 'services' }, { title: 'See fees', description: 'Get consultation and package fee details', rowId: 'pricing' }, { title: 'Talk to reception', description: 'Get help from the clinic team', rowId: 'support' }] }] }, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'send-agent', type: 'send', position: P(700, 380), data: { sendMode: 'text', message: 'I am connecting you to the clinic team now.', footer: '', title: '', buttons: [], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'handoff-1', type: 'handoff', position: P(700, 540), data: { reason: 'router escalation', note: 'AI router detected a support or escalation request.', assignee: '' } },
      { id: 'ai-1', type: 'ai', position: P(920, 380), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a concise clinic WhatsApp assistant. Answer clearly, ask one follow-up question if needed, and invite the patient to ask for booking, fees, or reception help if relevant.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'send-pricing', 'route_1'),
      edge('router-1', 'book-1', 'route_2'),
      edge('router-1', 'send-menu', 'route_3'),
      edge('router-1', 'send-agent', 'route_4'),
      edge('send-agent', 'handoff-1'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  {
    id: 'ai-real-estate-router',
    name: 'AI Real Estate Router',
    industry: 'Real Estate',
    description: 'Use AI to decide whether a lead needs property options, a site visit, pricing help, human escalation, or a fallback answer.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(360, 20), data: { label: 'Property lead sends a message' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(360, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt: 'You route real-estate leads on WhatsApp. Choose listings when they want options in a location or budget, choose site visit when they want to schedule a visit, choose pricing when they ask about EMI, price, or offers, choose human support when they ask for an agent or have a complaint, and use fallback for general questions.',
          confidenceThreshold: 0.55,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Show listings', description: 'Lead wants available properties, options, location matches, or inventory.' },
            { id: 'route_2', label: 'Book site visit', description: 'Lead wants to schedule a site visit or a call-back time.' },
            { id: 'route_3', label: 'Pricing help', description: 'Lead is asking about budget, payment plan, price, discount, or EMI.' },
            { id: 'route_4', label: 'Agent handoff', description: 'Lead explicitly asks for an agent, negotiation, or human help.' },
            { id: 'fallback', label: 'FAQ fallback', description: 'General question or low-confidence case. AI should answer and clarify.' },
          ],
        },
      },
      { id: 'cat-1', type: 'catalog', position: P(70, 390), data: { productIds: [], message: 'Here are matching properties you can review first:' } },
      { id: 'book-1', type: 'booking', position: P(280, 390), data: { service: 'site visit', daysAhead: 6, startHour: 10, endHour: 18, intervalMins: 60, reminderHours: 24, message: 'Choose a site visit slot:', confirmMessage: 'Your site visit is booked for {{slot}}.' } },
      { id: 'send-pricing', type: 'send', position: P(500, 390), data: { sendMode: 'buttons', message: 'I can help with pricing and payment options.', footer: 'Choose one option', title: '', buttons: [{ type: 'cta_url', label: 'View price sheet', url: 'https://example.com/property-pricing' }, { type: 'quick_reply', label: 'Book site visit', id: 'book_visit' }], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'send-agent', type: 'send', position: P(720, 390), data: { sendMode: 'text', message: 'I am connecting you to the assigned property advisor now.', footer: '', title: '', buttons: [], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'handoff-1', type: 'handoff', position: P(720, 550), data: { reason: 'lead wants advisor', note: 'AI router escalated this real-estate lead to a human advisor.', assignee: '' } },
      { id: 'ai-1', type: 'ai', position: P(940, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a real-estate WhatsApp assistant. Answer clearly, ask for location or budget when needed, and invite the customer to request listings or a site visit.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'cat-1', 'route_1'),
      edge('router-1', 'book-1', 'route_2'),
      edge('router-1', 'send-pricing', 'route_3'),
      edge('router-1', 'send-agent', 'route_4'),
      edge('send-agent', 'handoff-1'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  {
    id: 'restaurant-order',
    name: 'Restaurant Menu And Order',
    industry: 'Food & Restaurant',
    description: 'Show menu products, collect intent, and send checkout.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'Food enquiry received' } },
      { id: 'cond-1', type: 'condition', position: P(300, 160), data: { matchType: 'contains', keyword: 'menu' } },
      { id: 'cat-1', type: 'catalog', position: P(140, 320), data: { productIds: [], message: 'Here is our menu:' } },
      { id: 'pay-1', type: 'payment', position: P(140, 480), data: { message: 'Complete your order payment here.', label: 'Pay now', linkTemplate: 'https://example.com/food-checkout?phone={{phone}}', currency: 'INR ' } },
      { id: 'send-1', type: 'send', position: P(500, 320), data: { sendMode: 'buttons', message: 'Would you like to see the menu?', footer: '', title: '', buttons: [{ type: 'quick_reply', label: 'Show menu', id: 'menu' }, { type: 'quick_reply', label: 'Talk to staff', id: 'agent' }], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
    ],
    edges: [
      edge('trigger-1', 'cond-1'),
      edge('cond-1', 'cat-1', 'true'),
      edge('cat-1', 'pay-1'),
      edge('cond-1', 'send-1', 'false'),
    ],
  },
  {
    id: 'support-handoff',
    name: 'Support FAQ And Human Handoff',
    industry: 'Support',
    description: 'Answer FAQs with AI and route agent requests to the team inbox.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'Support message received' } },
      { id: 'cond-1', type: 'condition', position: P(300, 160), data: { matchType: 'contains', keyword: 'agent' } },
      { id: 'send-1', type: 'send', position: P(120, 320), data: { sendMode: 'text', message: 'Connecting you to a team member.', footer: '', title: '', buttons: [], list: null, event: null, externalAdReply: null, template: null, product: null, carousel: null } },
      { id: 'handoff-1', type: 'handoff', position: P(120, 470), data: { reason: 'requested', note: 'Customer asked for a human.', assignee: '' } },
      { id: 'ai-1', type: 'ai', position: P(500, 320), data: { provider: 'openai', systemPrompt: 'You are a concise support assistant. Answer common questions and invite customers to type agent for human support.' } },
    ],
    edges: [
      edge('trigger-1', 'cond-1'),
      edge('cond-1', 'send-1', 'true'),
      edge('send-1', 'handoff-1'),
      edge('cond-1', 'ai-1', 'false'),
    ],
  },
]

const clone = (value) => JSON.parse(JSON.stringify(value))
const enabledTemplateIds = new Set(['clinic-appointment-router', 'ai-smart-front-desk'])

export const workflowTemplateList = () =>
  TEMPLATES.filter((template) => enabledTemplateIds.has(template.id)).map((template) => ({
    id: template.id,
    name: template.name,
    industry: template.industry,
    description: template.description,
    nodes: clone(template.nodes),
    edges: clone(template.edges),
  }))

export const getWorkflowTemplate = (id) =>
  workflowTemplateList().find((template) => template.id === id)
