const P = (x, y) => ({ x, y })

const edge = (source, target, sourceHandle = null) => ({
  id: `edge-${source}-${sourceHandle || 'default'}-${target}-default`,
  source,
  target,
  sourceHandle,
  targetHandle: null,
  animated: true,
})

const sendData = (overrides = {}) => ({
  sendMode: 'text',
  message: '',
  footer: '',
  title: '',
  buttons: [],
  list: null,
  event: null,
  externalAdReply: null,
  template: null,
  product: null,
  carousel: null,
  ...overrides,
})

const postJson = (url, bodyTemplate, saveAs) => ({
  method: 'POST',
  url,
  headers: [{ key: 'Content-Type', value: 'application/json' }],
  bodyTemplate,
  saveAs,
})

const TEMPLATES = [
  {
    id: 'simple-appointment-menu',
    name: 'Simple Appointment Menu',
    industry: 'Clinic / Healthcare',
    description:
      'Shows a simple menu. Patients can book a visit, check doctor timings, see visit prep, or get clinic info.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(420, 20), data: { label: 'Patient sends a message' } },
      { id: 'cond-book', type: 'condition', position: P(420, 140), data: { matchType: 'equals', keyword: 'book_visit' } },
      { id: 'book-1', type: 'booking', position: P(40, 320), data: { service: 'clinic appointment', daysAhead: 7, startHour: 9, endHour: 18, intervalMins: 30, reminderHours: 24, buttonText: 'Pick a date and time', message: 'Choose your appointment time:', confirmMessage: 'Your appointment is booked for {{slot}}.' } },
      { id: 'api-booking', type: 'api', position: P(40, 500), data: postJson('https://example.com/api/clinic/appointments', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "source": "deterministic_menu"\n}', 'appointment') },
      { id: 'send-booked', type: 'send', position: P(40, 680), data: sendData({ sendMode: 'buttons', message: 'Booked for {{slot}}. Please come 10 minutes early and bring old reports if you have them.', footer: 'GrowCare Clinic', buttons: [{ type: 'quick_reply', label: 'Visit preparation', id: 'visit_prep' }, { type: 'quick_reply', label: 'Main menu', id: 'clinic_menu' }] }) },
      { id: 'schedule-reminder', type: 'schedule', position: P(40, 860), data: { seconds: 86400, message: 'Reminder: your appointment is at {{slot}}. Reply here if you need help before the visit.' } },

      { id: 'cond-availability', type: 'condition', position: P(420, 260), data: { matchType: 'equals', keyword: 'check_doctor' } },
      { id: 'send-doctor-menu', type: 'send', position: P(320, 440), data: sendData({ sendMode: 'list', message: 'Choose a doctor or department to check timing.', footer: 'Doctor availability', list: { title: 'Doctor timing menu', buttonText: 'Open doctor list', sections: [{ title: 'Available options', rows: [{ title: 'General doctor', description: 'Morning and evening clinic timings', rowId: 'doctor_general' }, { title: 'Dental doctor', description: 'Dental OP timings', rowId: 'doctor_dental' }, { title: 'Skin doctor', description: 'Skin clinic timings', rowId: 'doctor_skin' }] }] } }) },

      { id: 'cond-prep', type: 'condition', position: P(420, 380), data: { matchType: 'equals', keyword: 'visit_prep' } },
      { id: 'send-prep', type: 'send', position: P(600, 560), data: sendData({ sendMode: 'buttons', message: 'Before your visit, please keep your old reports, prescriptions, and current medicine list ready. Please arrive 10 minutes early.', footer: 'Visit preparation', buttons: [{ type: 'quick_reply', label: 'Book appointment', id: 'book_visit' }, { type: 'quick_reply', label: 'Main menu', id: 'clinic_menu' }] }) },

      { id: 'cond-info', type: 'condition', position: P(420, 500), data: { matchType: 'equals', keyword: 'clinic_info' } },
      { id: 'send-info', type: 'send', position: P(880, 680), data: sendData({ sendMode: 'buttons', message: 'Clinic timing: 9 AM to 6 PM.\nLocation: Main Road, City Center.\nFor support, you can call or reply here.', footer: 'Clinic information', buttons: [{ type: 'cta_call', label: 'Call clinic', phoneNumber: '+911234567890' }, { type: 'quick_reply', label: 'Main menu', id: 'clinic_menu' }] }) },

      { id: 'cond-general', type: 'condition', position: P(420, 620), data: { matchType: 'equals', keyword: 'doctor_general' } },
      { id: 'send-general', type: 'send', position: P(220, 800), data: sendData({ sendMode: 'buttons', message: 'General doctor is available Monday to Saturday, 10 AM to 1 PM and 5 PM to 7 PM.', footer: 'Doctor timing', buttons: [{ type: 'quick_reply', label: 'Book appointment', id: 'book_visit' }, { type: 'quick_reply', label: 'Main menu', id: 'clinic_menu' }] }) },

      { id: 'cond-dental', type: 'condition', position: P(420, 740), data: { matchType: 'equals', keyword: 'doctor_dental' } },
      { id: 'send-dental', type: 'send', position: P(500, 920), data: sendData({ sendMode: 'buttons', message: 'Dental doctor is available Tuesday to Sunday, 11 AM to 4 PM.', footer: 'Doctor timing', buttons: [{ type: 'quick_reply', label: 'Book appointment', id: 'book_visit' }, { type: 'quick_reply', label: 'Main menu', id: 'clinic_menu' }] }) },

      { id: 'cond-skin', type: 'condition', position: P(420, 860), data: { matchType: 'equals', keyword: 'doctor_skin' } },
      { id: 'send-skin', type: 'send', position: P(780, 1040), data: sendData({ sendMode: 'buttons', message: 'Skin doctor is available Wednesday and Saturday, 2 PM to 6 PM.', footer: 'Doctor timing', buttons: [{ type: 'quick_reply', label: 'Book appointment', id: 'book_visit' }, { type: 'quick_reply', label: 'Main menu', id: 'clinic_menu' }] }) },

      { id: 'cond-menu', type: 'condition', position: P(420, 980), data: { matchType: 'equals', keyword: 'clinic_menu' } },
      { id: 'send-menu', type: 'send', position: P(1080, 1160), data: sendData({ sendMode: 'list', message: 'Welcome to GrowCare Clinic. Choose one option below.', footer: 'Main menu', list: { title: 'Appointment menu', buttonText: 'Open menu', sections: [{ title: 'Choose one', rows: [{ title: 'Book appointment', description: 'Pick date and time', rowId: 'book_visit' }, { title: 'Check doctor availability', description: 'See doctor timings', rowId: 'check_doctor' }, { title: 'Visit preparation', description: 'See what to bring before your visit', rowId: 'visit_prep' }, { title: 'Other information', description: 'Clinic timing, location, and contact', rowId: 'clinic_info' }] }] } }) },
    ],
    edges: [
      edge('trigger-1', 'cond-book'),
      edge('cond-book', 'book-1', 'true'),
      edge('book-1', 'api-booking'),
      edge('api-booking', 'send-booked'),
      edge('send-booked', 'schedule-reminder'),
      edge('cond-book', 'cond-availability', 'false'),
      edge('cond-availability', 'send-doctor-menu', 'true'),
      edge('cond-availability', 'cond-prep', 'false'),
      edge('cond-prep', 'send-prep', 'true'),
      edge('cond-prep', 'cond-info', 'false'),
      edge('cond-info', 'send-info', 'true'),
      edge('cond-info', 'cond-general', 'false'),
      edge('cond-general', 'send-general', 'true'),
      edge('cond-general', 'cond-dental', 'false'),
      edge('cond-dental', 'send-dental', 'true'),
      edge('cond-dental', 'cond-skin', 'false'),
      edge('cond-skin', 'send-skin', 'true'),
      edge('cond-skin', 'cond-menu', 'false'),
      edge('cond-menu', 'send-menu', 'true'),
      edge('cond-menu', 'send-menu', 'false'),
    ],
  },
  {
    id: 'clinic-appointment-intake',
    name: 'Book Visit + Urgent Help',
    industry: 'Clinic / Healthcare',
    description:
      'Books a visit, sends urgent cases to staff, saves the booking, and sends reminders.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(420, 20), data: { label: 'Patient sends a WhatsApp message' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(420, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You work like a clinic front desk. If the patient wants a new appointment, choose booking. If the message sounds urgent or dangerous, choose urgent. If they want to change or cancel a visit, choose reschedule. If they ask about fees or insurance, choose fees. Use fallback for normal clinic questions. Do not diagnose.',
          confidenceThreshold: 0.58,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Book appointment', description: 'The patient wants to book a new visit.' },
            { id: 'route_2', label: 'Urgent symptoms', description: 'The patient says the problem is serious or urgent.' },
            { id: 'route_3', label: 'Reschedule or cancel', description: 'The patient wants to move or cancel a visit.' },
            { id: 'route_4', label: 'Fees or insurance', description: 'The patient asks about cost or insurance.' },
            { id: 'fallback', label: 'General questions', description: 'Normal questions like timing, doctor, location, or reports.' },
          ],
        },
      },
      { id: 'book-1', type: 'booking', position: P(60, 390), data: { service: 'consultation', daysAhead: 7, startHour: 9, endHour: 19, intervalMins: 30, reminderHours: 24, message: 'Choose a consultation slot:', confirmMessage: 'Your visit is reserved for {{slot}}. We will now prepare your intake.' } },
      { id: 'set-1', type: 'set', position: P(60, 550), data: { field: 'careStage', value: 'appointment_booked' } },
      { id: 'api-1', type: 'api', position: P(60, 710), data: postJson('https://example.com/api/clinic/appointments', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "careStage": "{{careStage}}",\n  "lastMessage": "{{message}}"\n}', 'appointment') },
      { id: 'send-confirm', type: 'send', position: P(60, 870), data: sendData({ sendMode: 'buttons', message: 'Booked for {{slot}}. Please bring previous prescriptions, reports, and ID proof.', footer: 'Reply if you need help before the visit', buttons: [{ type: 'quick_reply', label: 'Share symptoms', id: 'share_symptoms' }, { type: 'quick_reply', label: 'Talk to reception', id: 'agent' }] }) },
      { id: 'schedule-1', type: 'schedule', position: P(60, 1030), data: { seconds: 86400, message: 'Reminder: your appointment is tomorrow at {{slot}}. Please arrive 10 minutes early.' } },
      { id: 'schedule-2', type: 'schedule', position: P(60, 1190), data: { seconds: 10800, message: 'Before your visit, keep your reports ready and avoid missing the slot. Reply here if you need to reschedule.' } },
      { id: 'send-urgent', type: 'send', position: P(340, 390), data: sendData({ message: 'Your message sounds urgent. I am connecting you to the clinic team right away. If this is a medical emergency, please call emergency services immediately.', footer: 'Urgent support' }) },
      { id: 'handoff-urgent', type: 'handoff', position: P(340, 550), data: { reason: 'urgent_triage', note: 'Possible urgent symptoms. Staff should review this chat immediately and call the patient if needed.', assignee: 'triage-desk' } },
      { id: 'send-reschedule', type: 'send', position: P(620, 390), data: sendData({ sendMode: 'buttons', message: 'I can help the reception team reschedule or cancel your visit.', footer: 'Choose one option', buttons: [{ type: 'quick_reply', label: 'Reschedule', id: 'reschedule' }, { type: 'quick_reply', label: 'Cancel visit', id: 'cancel_visit' }] }) },
      { id: 'handoff-reschedule', type: 'handoff', position: P(620, 550), data: { reason: 'reschedule_request', note: 'Patient wants to change or cancel an existing booking. Staff should verify slot and update the booking.', assignee: 'front-desk' } },
      { id: 'send-fees', type: 'send', position: P(900, 390), data: sendData({ sendMode: 'buttons', message: 'Here are the quickest next steps for fee and insurance questions.', footer: 'Choose one option', buttons: [{ type: 'cta_url', label: 'View consultation fees', url: 'https://example.com/fees' }, { type: 'quick_reply', label: 'Talk to billing', id: 'billing_help' }] }) },
      { id: 'ai-1', type: 'ai', position: P(1180, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a clinic WhatsApp assistant. Help with clinic timings, visit prep, doctor availability, and what documents to bring. Keep replies short and simple. Do not diagnose.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'book-1', 'route_1'),
      edge('book-1', 'set-1'),
      edge('set-1', 'api-1'),
      edge('api-1', 'send-confirm'),
      edge('send-confirm', 'schedule-1'),
      edge('schedule-1', 'schedule-2'),
      edge('router-1', 'send-urgent', 'route_2'),
      edge('send-urgent', 'handoff-urgent'),
      edge('router-1', 'send-reschedule', 'route_3'),
      edge('send-reschedule', 'handoff-reschedule'),
      edge('router-1', 'send-fees', 'route_4'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  {
    id: 'clinic-smart-front-desk',
    name: 'Smart Front Desk',
    industry: 'Clinic / Healthcare',
    description:
      'Sorts messages into booking, billing, department help, staff support, or general questions.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(380, 20), data: { label: 'Patient message reaches the clinic inbox' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(380, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You are a clinic receptionist. Send booking requests to appointments. Send fee or insurance questions to billing. Send department or service questions to the options menu. Send complaints or staff requests to human handoff. Use fallback for normal questions.',
          confidenceThreshold: 0.58,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Fees and billing', description: 'Cost, estimate, insurance, or receipt question.' },
            { id: 'route_2', label: 'Appointment booking', description: 'The patient wants to book or confirm a slot.' },
            { id: 'route_3', label: 'Departments and services', description: 'The patient wants help choosing a doctor or service.' },
            { id: 'route_4', label: 'Reception handoff', description: 'The patient wants a real person or has a complaint.' },
            { id: 'fallback', label: 'General questions', description: 'Any normal clinic question.' },
          ],
        },
      },
      { id: 'send-fees', type: 'send', position: P(40, 390), data: sendData({ sendMode: 'buttons', message: 'Here are the quickest ways to handle fees and billing.', footer: 'Billing desk support', buttons: [{ type: 'cta_url', label: 'View fees', url: 'https://example.com/fees' }, { type: 'quick_reply', label: 'Insurance help', id: 'insurance_help' }] }) },
      { id: 'book-1', type: 'booking', position: P(300, 390), data: { service: 'consultation', daysAhead: 5, startHour: 10, endHour: 18, intervalMins: 30, reminderHours: 24, message: 'Pick a consultation time:', confirmMessage: 'Your consultation is confirmed for {{slot}}.' } },
      { id: 'api-1', type: 'api', position: P(300, 550), data: postJson('https://example.com/api/clinic/front-desk-bookings', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "route": "{{router.label}}"\n}', 'frontDeskBooking') },
      { id: 'send-booked', type: 'send', position: P(300, 710), data: sendData({ message: 'Your consultation is booked for {{slot}}. Reply here anytime if you need help before the visit.', footer: 'GrowCare Clinic' }) },
      { id: 'send-menu', type: 'send', position: P(580, 390), data: sendData({ sendMode: 'list', message: 'Choose the department or help area you need.', footer: 'Select one option', list: { title: 'Clinic options', buttonText: 'Open options', sections: [{ title: 'Popular paths', rows: [{ title: 'General medicine', description: 'Routine visit, fever, pain, follow-up', rowId: 'general_medicine' }, { title: 'Diagnostics and reports', description: 'Book tests or ask about results', rowId: 'diagnostics' }, { title: 'Billing and insurance', description: 'Fees, bills, and receipts', rowId: 'billing' }] }] } }) },
      { id: 'send-agent', type: 'send', position: P(860, 390), data: sendData({ message: 'I am connecting you to the clinic team now.', footer: 'Human support' }) },
      { id: 'handoff-1', type: 'handoff', position: P(860, 550), data: { reason: 'front_desk_escalation', note: 'Patient requested human support or raised a complaint. Reception should review the full chat.', assignee: 'front-desk' } },
      { id: 'ai-1', type: 'ai', position: P(1140, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a clinic WhatsApp assistant. Answer simple questions about timing, doctors, reports, location, and visit prep. Keep answers short. Do not diagnose.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'send-fees', 'route_1'),
      edge('router-1', 'book-1', 'route_2'),
      edge('book-1', 'api-1'),
      edge('api-1', 'send-booked'),
      edge('router-1', 'send-menu', 'route_3'),
      edge('router-1', 'send-agent', 'route_4'),
      edge('send-agent', 'handoff-1'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  {
    id: 'diagnostics-report-desk',
    name: 'Tests + Reports Desk',
    industry: 'Clinic / Healthcare',
    description:
      'Helps patients upload reports, book tests, check report status, or talk to the lab desk.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(400, 20), data: { label: 'Patient asks about tests, scans, or reports' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(400, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You help with clinic tests and reports. Send upload requests to the upload path. Send test booking requests to booking. Send report status questions to report help. Send staff requests to human handoff. Use fallback for other questions.',
          confidenceThreshold: 0.56,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Upload reports', description: 'The patient wants to send reports or prescriptions.' },
            { id: 'route_2', label: 'Book diagnostic slot', description: 'The patient wants to book a test or scan.' },
            { id: 'route_3', label: 'Result status', description: 'The patient wants to know if the report is ready.' },
            { id: 'route_4', label: 'Lab desk handoff', description: 'The patient wants a person or has a report issue.' },
            { id: 'fallback', label: 'General questions', description: 'Any normal test or report question.' },
          ],
        },
      },
      { id: 'send-upload', type: 'send', position: P(40, 390), data: sendData({ sendMode: 'buttons', message: 'You can upload prescriptions or old reports before the visit.', footer: 'Document collection', buttons: [{ type: 'cta_url', label: 'Upload reports', url: 'https://example.com/reports/upload' }, { type: 'quick_reply', label: 'Need help', id: 'report_help' }] }) },
      { id: 'api-upload', type: 'api', position: P(40, 550), data: postJson('https://example.com/api/clinic/report-uploads', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "requestType": "report_upload",\n  "message": "{{message}}"\n}', 'reportUpload') },
      { id: 'schedule-upload', type: 'schedule', position: P(40, 710), data: { seconds: 21600, message: 'Friendly reminder: please upload the requested reports before your diagnostic visit.' } },
      { id: 'book-1', type: 'booking', position: P(320, 390), data: { service: 'diagnostic slot', daysAhead: 6, startHour: 8, endHour: 18, intervalMins: 30, reminderHours: 24, message: 'Choose a time for your diagnostic slot:', confirmMessage: 'Your diagnostic slot is booked for {{slot}}.' } },
      { id: 'api-booking', type: 'api', position: P(320, 550), data: postJson('https://example.com/api/clinic/diagnostics-bookings', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "testRequest": "{{message}}"\n}', 'diagnosticBooking') },
      { id: 'send-booked', type: 'send', position: P(320, 710), data: sendData({ message: 'Booked for {{slot}}. Please carry your doctor note, previous results, and fasting instructions if applicable.', footer: 'Diagnostics desk' }) },
      { id: 'send-results', type: 'send', position: P(640, 390), data: sendData({ sendMode: 'list', message: 'Choose the report support option you need.', footer: 'Select one option', list: { title: 'Report options', buttonText: 'Open options', sections: [{ title: 'Diagnostics support', rows: [{ title: 'Report ready status', description: 'Check if your report is ready', rowId: 'report_ready' }, { title: 'Email me the report', description: 'Request a digital copy', rowId: 'email_report' }, { title: 'Talk to lab desk', description: 'Get manual help from the team', rowId: 'lab_support' }] }] } }) },
      { id: 'send-agent', type: 'send', position: P(920, 390), data: sendData({ message: 'I am connecting you to the diagnostics desk now.', footer: 'Human support' }) },
      { id: 'handoff-1', type: 'handoff', position: P(920, 550), data: { reason: 'diagnostics_support', note: 'Patient needs report or diagnostics coordination from a staff member.', assignee: 'lab-desk' } },
      { id: 'ai-1', type: 'ai', position: P(1200, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a diagnostics desk assistant. Help with fasting rules, report timing, sample collection time, and what to bring. Do not explain medical results.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'send-upload', 'route_1'),
      edge('send-upload', 'api-upload'),
      edge('api-upload', 'schedule-upload'),
      edge('router-1', 'book-1', 'route_2'),
      edge('book-1', 'api-booking'),
      edge('api-booking', 'send-booked'),
      edge('router-1', 'send-results', 'route_3'),
      edge('router-1', 'send-agent', 'route_4'),
      edge('send-agent', 'handoff-1'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  // ── DETERMINISTIC / MENU-BASED TEMPLATES ──────────────────────────────

  {
    id: 'appointment-reminder-cascade',
    name: 'Appointment Reminder Cascade',
    industry: 'Clinic / Healthcare',
    description:
      'Sends a confirmation request 48 h before the visit, a prep checklist 24 h before, and a final nudge 2 h before. No AI — pure schedule drip with YES / NO branching.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(360, 20), data: { label: 'Booking confirmed — start reminder cascade' } },
      { id: 'send-confirm-ask', type: 'send', position: P(360, 160), data: sendData({ sendMode: 'buttons', message: 'Hi! Your appointment is in 2 days at {{slot}}. Please confirm you will attend.', footer: 'Tap one option to confirm', buttons: [{ type: 'quick_reply', label: 'Yes, I will be there', id: 'confirm_yes' }, { type: 'quick_reply', label: 'Need to reschedule', id: 'confirm_no' }] }) },
      { id: 'cond-confirm', type: 'condition', position: P(360, 320), data: { matchType: 'equals', keyword: 'confirm_yes' } },
      { id: 'send-confirmed', type: 'send', position: P(80, 480), data: sendData({ message: 'Perfect, your slot at {{slot}} is confirmed. We look forward to seeing you.', footer: 'GrowCare Clinic' }) },
      { id: 'sched-prep', type: 'schedule', position: P(80, 640), data: { seconds: 86400, message: 'Visit checklist for tomorrow at {{slot}}:\n\n✅ Carry old prescriptions and reports\n✅ Bring a valid photo ID\n✅ Note any new symptoms since last visit\n✅ Arrive 10 minutes early\n\nReply here if you have any questions.' } },
      { id: 'sched-day', type: 'schedule', position: P(80, 800), data: { seconds: 7200, message: 'Your appointment is today at {{slot}}. Please head to the clinic now. Reply if you need directions or are running late.' } },
      { id: 'send-reschedule', type: 'send', position: P(640, 480), data: sendData({ message: 'No problem. I am forwarding your reschedule request to the front desk. Someone will confirm your new slot shortly.', footer: 'Front desk support' }) },
      { id: 'handoff-reschedule', type: 'handoff', position: P(640, 640), data: { reason: 'reschedule_requested', note: 'Patient confirmed they cannot attend the slot at {{slot}}. Please call and rebook.', assignee: 'front-desk' } },
    ],
    edges: [
      edge('trigger-1', 'send-confirm-ask'),
      edge('send-confirm-ask', 'cond-confirm'),
      edge('cond-confirm', 'send-confirmed', 'true'),
      edge('send-confirmed', 'sched-prep'),
      edge('sched-prep', 'sched-day'),
      edge('cond-confirm', 'send-reschedule', 'false'),
      edge('send-reschedule', 'handoff-reschedule'),
    ],
  },

  {
    id: 'feedback-collection',
    name: 'Post-Visit Feedback',
    industry: 'Clinic / Healthcare',
    description:
      'Asks patients to rate their visit experience by replying 1, 2, or 3. Saves the rating and escalates poor feedback to the clinic manager. Fully deterministic — no AI.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'Send after visit is completed' } },
      { id: 'send-ask', type: 'send', position: P(300, 160), data: sendData({ message: 'Thank you for visiting GrowCare Clinic today. How was your experience?\n\nReply:\n*1* — Excellent\n*2* — Good\n*3* — Needs improvement', footer: 'Takes 5 seconds · Fully anonymous' }) },
      { id: 'cond-1', type: 'condition', position: P(300, 320), data: { matchType: 'equals', keyword: '1' } },
      { id: 'send-excellent', type: 'send', position: P(60, 480), data: sendData({ message: 'Thank you! We are so glad you had a great experience. See you on your next visit. 🌟', footer: 'GrowCare Clinic' }) },
      { id: 'api-excellent', type: 'api', position: P(60, 640), data: postJson('https://example.com/api/clinic/feedback', '{\n  "phone": "{{phone}}",\n  "rating": 1,\n  "label": "Excellent"\n}', 'feedback') },
      { id: 'cond-2', type: 'condition', position: P(300, 480), data: { matchType: 'equals', keyword: '2' } },
      { id: 'send-good', type: 'send', position: P(340, 640), data: sendData({ message: 'Thank you for your feedback! We are always working to improve. See you soon. 😊', footer: 'GrowCare Clinic' }) },
      { id: 'api-good', type: 'api', position: P(340, 800), data: postJson('https://example.com/api/clinic/feedback', '{\n  "phone": "{{phone}}",\n  "rating": 2,\n  "label": "Good"\n}', 'feedback') },
      { id: 'cond-3', type: 'condition', position: P(300, 640), data: { matchType: 'equals', keyword: '3' } },
      { id: 'send-poor', type: 'send', position: P(600, 800), data: sendData({ message: 'We are sorry to hear that. A clinic manager will review your visit and follow up with you shortly.', footer: 'We take your feedback seriously' }) },
      { id: 'api-poor', type: 'api', position: P(600, 960), data: postJson('https://example.com/api/clinic/feedback', '{\n  "phone": "{{phone}}",\n  "rating": 3,\n  "label": "Needs improvement"\n}', 'feedback') },
      { id: 'handoff-poor', type: 'handoff', position: P(600, 1120), data: { reason: 'poor_feedback', note: 'Patient rated the visit 3 — Needs improvement. Review the visit notes and follow up within 24 hours.', assignee: 'clinic-manager' } },
    ],
    edges: [
      edge('trigger-1', 'send-ask'),
      edge('send-ask', 'cond-1'),
      edge('cond-1', 'send-excellent', 'true'),
      edge('send-excellent', 'api-excellent'),
      edge('cond-1', 'cond-2', 'false'),
      edge('cond-2', 'send-good', 'true'),
      edge('send-good', 'api-good'),
      edge('cond-2', 'cond-3', 'false'),
      edge('cond-3', 'send-poor', 'true'),
      edge('send-poor', 'api-poor'),
      edge('api-poor', 'handoff-poor'),
    ],
  },

  {
    id: 'discharge-care-protocol',
    name: 'Discharge Care Protocol',
    industry: 'Clinic / Healthcare',
    description:
      'Runs a structured check-in schedule after discharge: medication reminder at 4 h, symptom check at 24 h, wound check at 48 h, and a week-1 review reminder at 7 days. All branched on YES / NO replies.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'Patient discharged — start care protocol' } },
      { id: 'send-discharge', type: 'send', position: P(300, 160), data: sendData({ sendMode: 'buttons', message: 'You have been discharged. Here are your care instructions:\n\n• Take medicines as prescribed\n• Rest and avoid heavy activity\n• Keep the wound site clean and dry\n• Return immediately if symptoms worsen\n\nWe will check on you shortly.', footer: 'GrowCare Discharge Team', buttons: [{ type: 'cta_url', label: 'Download instructions', url: 'https://example.com/discharge-instructions' }, { type: 'quick_reply', label: 'Talk to nurse', id: 'nurse_help' }] }) },
      { id: 'sched-meds', type: 'schedule', position: P(300, 320), data: { seconds: 14400, message: '💊 Medicine reminder: Time to take your 4-hour dose. Please take your medicines with water as prescribed. Reply DONE when taken.' } },
      { id: 'cond-done', type: 'condition', position: P(300, 480), data: { matchType: 'equals', keyword: 'DONE' } },
      { id: 'send-med-ok', type: 'send', position: P(80, 640), data: sendData({ message: 'Great! Keep it up. Consistent medicine timing is very important for recovery. We will check in again tomorrow.', footer: 'GrowCare Care Team' }) },
      { id: 'sched-day1', type: 'schedule', position: P(80, 800), data: { seconds: 86400, message: 'Day 1 check-in: How are you feeling today?\n\nReply:\n*GOOD* — recovering normally\n*CONCERN* — something feels wrong' } },
      { id: 'cond-day1', type: 'condition', position: P(80, 960), data: { matchType: 'equals', keyword: 'GOOD' } },
      { id: 'send-day1-ok', type: 'send', position: P(80, 1120), data: sendData({ message: 'Wonderful! Rest well and take your medicines on time. We will check again at 48 hours.', footer: 'Day 1 all clear' }) },
      { id: 'sched-day2', type: 'schedule', position: P(80, 1280), data: { seconds: 86400, message: 'Day 2 wound check: Please check the wound area.\n\nIs there any redness, swelling, pain, or discharge?\n\nReply *YES* or *NO*' } },
      { id: 'cond-day2', type: 'condition', position: P(80, 1440), data: { matchType: 'equals', keyword: 'NO' } },
      { id: 'send-day2-ok', type: 'send', position: P(80, 1600), data: sendData({ message: 'Great news! Recovery is on track. We will remind you about your week-1 review visit.', footer: 'Day 2 all clear' }) },
      { id: 'sched-week1', type: 'schedule', position: P(80, 1760), data: { seconds: 432000, message: 'Week 1 follow-up reminder: Time to book your post-discharge review. Reply BOOK to get a slot or call us directly.' } },
      { id: 'send-concern', type: 'send', position: P(560, 640), data: sendData({ message: 'Thank you for letting us know. Do not worry — the care team is being alerted right now. If you have severe symptoms, please go to the nearest emergency room immediately.', footer: 'Urgent care team notified' }) },
      { id: 'handoff-concern', type: 'handoff', position: P(560, 800), data: { reason: 'discharge_red_flag', note: 'Patient reported a concern after discharge. Review the chart and call immediately.', assignee: 'doctor-assist' } },
      { id: 'send-wound-yes', type: 'send', position: P(560, 1280), data: sendData({ message: 'Please do not ignore this. I am alerting the nursing team now. Please keep the area clean and do not touch the wound.', footer: 'Wound care alert' }) },
      { id: 'handoff-wound', type: 'handoff', position: P(560, 1440), data: { reason: 'wound_complication', note: 'Patient reports redness, swelling, or discharge at wound site on Day 2. Needs urgent nurse or doctor review.', assignee: 'wound-care' } },
    ],
    edges: [
      edge('trigger-1', 'send-discharge'),
      edge('send-discharge', 'sched-meds'),
      edge('sched-meds', 'cond-done'),
      edge('cond-done', 'send-med-ok', 'true'),
      edge('send-med-ok', 'sched-day1'),
      edge('sched-day1', 'cond-day1'),
      edge('cond-day1', 'send-day1-ok', 'true'),
      edge('send-day1-ok', 'sched-day2'),
      edge('sched-day2', 'cond-day2'),
      edge('cond-day2', 'send-day2-ok', 'true'),
      edge('send-day2-ok', 'sched-week1'),
      edge('cond-day1', 'send-concern', 'false'),
      edge('send-concern', 'handoff-concern'),
      edge('cond-day2', 'send-wound-yes', 'false'),
      edge('send-wound-yes', 'handoff-wound'),
    ],
  },

  {
    id: 'specialist-referral-menu',
    name: 'Specialist Referral Routing',
    industry: 'Clinic / Healthcare',
    description:
      'Shows a department list when a patient is referred. Each department choice opens the correct booking slot. Fully menu-driven — no AI required.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(380, 20), data: { label: 'Patient referred — choose specialist department' } },
      { id: 'send-dept-menu', type: 'send', position: P(380, 160), data: sendData({ sendMode: 'list', message: 'You have been referred for a specialist consultation. Please choose the department from the list below and we will book your slot.', footer: 'Select your department', list: { title: 'Specialist departments', buttonText: 'Choose department', sections: [{ title: 'Available specialties', rows: [{ title: 'General Medicine', description: 'Routine, fever, pain, follow-up', rowId: 'ref_general' }, { title: 'Cardiology', description: 'Heart, BP, ECG, and chest concerns', rowId: 'ref_cardiology' }, { title: 'Neurology', description: 'Headache, vertigo, nerve concerns', rowId: 'ref_neurology' }, { title: 'Orthopedics', description: 'Bone, joint, muscle, and spine', rowId: 'ref_ortho' }, { title: 'Dermatology', description: 'Skin, hair, and nail concerns', rowId: 'ref_derma' }] }] } }) },
      { id: 'cond-gen', type: 'condition', position: P(380, 340), data: { matchType: 'equals', keyword: 'ref_general' } },
      { id: 'book-gen', type: 'booking', position: P(40, 520), data: { service: 'General Medicine consultation', daysAhead: 5, startHour: 9, endHour: 18, intervalMins: 30, reminderHours: 24, message: 'Choose your General Medicine slot:', confirmMessage: 'Your General Medicine appointment is confirmed for {{slot}}.' } },
      { id: 'cond-cardio', type: 'condition', position: P(380, 520), data: { matchType: 'equals', keyword: 'ref_cardiology' } },
      { id: 'book-cardio', type: 'booking', position: P(240, 700), data: { service: 'Cardiology consultation', daysAhead: 7, startHour: 10, endHour: 17, intervalMins: 30, reminderHours: 24, message: 'Choose your Cardiology slot:', confirmMessage: 'Your Cardiology appointment is confirmed for {{slot}}. Please bring previous ECG and BP records.' } },
      { id: 'cond-neuro', type: 'condition', position: P(380, 700), data: { matchType: 'equals', keyword: 'ref_neurology' } },
      { id: 'book-neuro', type: 'booking', position: P(440, 880), data: { service: 'Neurology consultation', daysAhead: 7, startHour: 10, endHour: 16, intervalMins: 20, reminderHours: 24, message: 'Choose your Neurology slot:', confirmMessage: 'Your Neurology appointment is confirmed for {{slot}}. Please bring previous MRI or CT reports if available.' } },
      { id: 'cond-ortho', type: 'condition', position: P(380, 880), data: { matchType: 'equals', keyword: 'ref_ortho' } },
      { id: 'book-ortho', type: 'booking', position: P(640, 1060), data: { service: 'Orthopedics consultation', daysAhead: 5, startHour: 9, endHour: 17, intervalMins: 30, reminderHours: 24, message: 'Choose your Orthopedics slot:', confirmMessage: 'Your Orthopedics appointment is confirmed for {{slot}}. Please bring previous X-rays or scans.' } },
      { id: 'cond-derma', type: 'condition', position: P(380, 1060), data: { matchType: 'equals', keyword: 'ref_derma' } },
      { id: 'book-derma', type: 'booking', position: P(840, 1240), data: { service: 'Dermatology consultation', daysAhead: 5, startHour: 10, endHour: 18, intervalMins: 20, reminderHours: 24, message: 'Choose your Dermatology slot:', confirmMessage: 'Your Dermatology appointment is confirmed for {{slot}}.' } },
      { id: 'send-fallback', type: 'send', position: P(1040, 1240), data: sendData({ message: 'I did not catch your department selection. Please reply with the department name (e.g. Cardiology, Neurology) and we will book the right slot.', footer: 'Please choose a department' }) },
      { id: 'send-booked', type: 'send', position: P(480, 1420), data: sendData({ message: 'Booking confirmed for {{slot}}. Please bring your referral letter, previous reports, and ID. Reply here if you need to reschedule.', footer: 'Specialist booking confirmed' }) },
    ],
    edges: [
      edge('trigger-1', 'send-dept-menu'),
      edge('send-dept-menu', 'cond-gen'),
      edge('cond-gen', 'book-gen', 'true'),
      edge('book-gen', 'send-booked'),
      edge('cond-gen', 'cond-cardio', 'false'),
      edge('cond-cardio', 'book-cardio', 'true'),
      edge('book-cardio', 'send-booked'),
      edge('cond-cardio', 'cond-neuro', 'false'),
      edge('cond-neuro', 'book-neuro', 'true'),
      edge('book-neuro', 'send-booked'),
      edge('cond-neuro', 'cond-ortho', 'false'),
      edge('cond-ortho', 'book-ortho', 'true'),
      edge('book-ortho', 'send-booked'),
      edge('cond-ortho', 'cond-derma', 'false'),
      edge('cond-derma', 'book-derma', 'true'),
      edge('book-derma', 'send-booked'),
      edge('cond-derma', 'send-fallback', 'false'),
    ],
  },

  {
    id: 'emergency-triage-gateway',
    name: 'Emergency Triage Gateway',
    industry: 'Clinic / Healthcare',
    description:
      'First message determines urgency. Emergency → immediate staff handoff. Urgent → same-day booking. Routine → normal slot. General question → AI. Fully button and keyword driven.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(380, 20), data: { label: 'Patient contacts the clinic' } },
      { id: 'send-triage', type: 'send', position: P(380, 160), data: sendData({ sendMode: 'buttons', message: 'Welcome to GrowCare Clinic. How can we help you today?', footer: 'Tap the option that best describes your need', buttons: [{ type: 'quick_reply', label: 'Emergency / Very urgent', id: 'triage_emergency' }, { type: 'quick_reply', label: 'Same-day urgent visit', id: 'triage_urgent' }, { type: 'quick_reply', label: 'Routine appointment', id: 'triage_routine' }] }) },
      { id: 'cond-emergency', type: 'condition', position: P(380, 320), data: { matchType: 'equals', keyword: 'triage_emergency' } },
      { id: 'send-emergency', type: 'send', position: P(40, 480), data: sendData({ message: 'This sounds like a medical emergency. If you are in danger, please call emergency services (112) immediately.\n\nI am alerting the clinic triage team right now. Someone will call you within minutes.', footer: 'Emergency alert sent' }) },
      { id: 'handoff-emergency', type: 'handoff', position: P(40, 640), data: { reason: 'emergency_triage', note: 'URGENT: Patient reported emergency via WhatsApp. Call immediately. Do not wait.', assignee: 'triage-desk' } },
      { id: 'cond-urgent', type: 'condition', position: P(380, 480), data: { matchType: 'equals', keyword: 'triage_urgent' } },
      { id: 'send-urgent-info', type: 'send', position: P(300, 640), data: sendData({ message: 'Understood. We will get you seen today. Please describe your main symptom in one line so we can prepare the right doctor.', footer: 'Same-day triage' }) },
      { id: 'book-urgent', type: 'booking', position: P(300, 800), data: { service: 'urgent same-day consultation', daysAhead: 1, startHour: 8, endHour: 20, intervalMins: 15, reminderHours: 1, message: 'Choose an urgent slot for today:', confirmMessage: 'Urgent slot confirmed for {{slot}}. Please arrive in the next 20 minutes with any prior reports.' } },
      { id: 'cond-routine', type: 'condition', position: P(380, 640), data: { matchType: 'equals', keyword: 'triage_routine' } },
      { id: 'book-routine', type: 'booking', position: P(560, 800), data: { service: 'routine consultation', daysAhead: 7, startHour: 9, endHour: 18, intervalMins: 30, reminderHours: 24, message: 'Choose a convenient slot:', confirmMessage: 'Your routine appointment is confirmed for {{slot}}.' } },
      { id: 'ai-general', type: 'ai', position: P(820, 800), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a clinic front-desk assistant. Help with clinic timings, fees, doctor availability, and directions. Never diagnose. If anything sounds urgent, advise the patient to call emergency services or visit in person.' } },
    ],
    edges: [
      edge('trigger-1', 'send-triage'),
      edge('send-triage', 'cond-emergency'),
      edge('cond-emergency', 'send-emergency', 'true'),
      edge('send-emergency', 'handoff-emergency'),
      edge('cond-emergency', 'cond-urgent', 'false'),
      edge('cond-urgent', 'send-urgent-info', 'true'),
      edge('send-urgent-info', 'book-urgent'),
      edge('cond-urgent', 'cond-routine', 'false'),
      edge('cond-routine', 'book-routine', 'true'),
      edge('cond-routine', 'ai-general', 'false'),
    ],
  },

  {
    id: 'medication-reminder-drip',
    name: 'Daily Medication Reminders',
    industry: 'Clinic / Healthcare',
    description:
      'Sends morning, afternoon, and evening medicine reminders. Waits for a DONE reply before sending the next nudge. Automatically restarts the next morning. No AI — pure schedule and condition chain.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'Patient enrolled in medication reminder program' } },
      { id: 'send-morning', type: 'send', position: P(300, 160), data: sendData({ message: '☀️ Good morning! Time for your morning medicines.\n\nPlease take your prescribed tablets with water. Reply *DONE* once taken.', footer: 'Morning dose reminder' }) },
      { id: 'cond-morning-done', type: 'condition', position: P(300, 320), data: { matchType: 'equals', keyword: 'DONE' } },
      { id: 'send-morning-ack', type: 'send', position: P(80, 480), data: sendData({ message: 'Well done! Keep it up 👍 Morning dose recorded. I will remind you at your afternoon dose time.', footer: 'Dose 1 of 3 done' }) },
      { id: 'sched-afternoon', type: 'schedule', position: P(80, 640), data: { seconds: 21600, message: '🌤️ Afternoon medicine reminder! Time for your midday dose. Please take it with food or water as prescribed. Reply *DONE* when taken.' } },
      { id: 'cond-afternoon-done', type: 'condition', position: P(80, 800), data: { matchType: 'equals', keyword: 'DONE' } },
      { id: 'send-afternoon-ack', type: 'send', position: P(80, 960), data: sendData({ message: 'Afternoon dose recorded. You are doing great! Evening reminder coming up later.', footer: 'Dose 2 of 3 done' }) },
      { id: 'sched-evening', type: 'schedule', position: P(80, 1120), data: { seconds: 21600, message: '🌙 Evening medicine reminder! Time for your night dose. Take it as prescribed and rest well. Reply *DONE* when taken.' } },
      { id: 'cond-evening-done', type: 'condition', position: P(80, 1280), data: { matchType: 'equals', keyword: 'DONE' } },
      { id: 'send-evening-ack', type: 'send', position: P(80, 1440), data: sendData({ message: 'All 3 doses done for today! ✅ Excellent discipline. Rest well and we will remind you again tomorrow morning.', footer: 'All doses complete for today' }) },
      { id: 'sched-tomorrow', type: 'schedule', position: P(80, 1600), data: { seconds: 43200, message: '☀️ Good morning! A new day — time for your morning medicines. Reply *DONE* once taken.' } },
      { id: 'send-morning-miss', type: 'send', position: P(540, 480), data: sendData({ message: 'Gentle nudge: did you take your morning medicines? It is important not to skip doses. Reply *DONE* when taken.', footer: 'Please do not miss a dose' }) },
      { id: 'send-afternoon-miss', type: 'send', position: P(540, 800), data: sendData({ message: 'Did you take your afternoon dose? Please take it soon if you have not. Reply *DONE* once done.', footer: 'Dose reminder' }) },
      { id: 'send-evening-miss', type: 'send', position: P(540, 1280), data: sendData({ message: 'Please remember your evening dose before sleeping. Reply *DONE* once taken. If you have missed a dose, contact your doctor.', footer: 'Evening dose reminder' }) },
    ],
    edges: [
      edge('trigger-1', 'send-morning'),
      edge('send-morning', 'cond-morning-done'),
      edge('cond-morning-done', 'send-morning-ack', 'true'),
      edge('send-morning-ack', 'sched-afternoon'),
      edge('sched-afternoon', 'cond-afternoon-done'),
      edge('cond-afternoon-done', 'send-afternoon-ack', 'true'),
      edge('send-afternoon-ack', 'sched-evening'),
      edge('sched-evening', 'cond-evening-done'),
      edge('cond-evening-done', 'send-evening-ack', 'true'),
      edge('send-evening-ack', 'sched-tomorrow'),
      edge('cond-morning-done', 'send-morning-miss', 'false'),
      edge('cond-afternoon-done', 'send-afternoon-miss', 'false'),
      edge('cond-evening-done', 'send-evening-miss', 'false'),
    ],
  },

  {
    id: 'lab-result-ready',
    name: 'Lab Result Ready Notification',
    industry: 'Clinic / Healthcare',
    description:
      'Notifies the patient when a lab report is ready. Offers three choices: view online, email the report, or talk to the lab desk. Fully button and condition driven.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(360, 20), data: { label: 'Lab marks report as ready — notify patient' } },
      { id: 'send-ready', type: 'send', position: P(360, 160), data: sendData({ sendMode: 'buttons', message: 'Your lab report is ready! 🧪\n\nHow would you like to access it?', footer: 'Choose one option', buttons: [{ type: 'cta_url', label: 'View report online', url: 'https://example.com/reports/view?phone={{phone}}' }, { type: 'quick_reply', label: 'Email me the report', id: 'email_report' }, { type: 'quick_reply', label: 'Talk to lab desk', id: 'lab_desk' }] }) },
      { id: 'cond-email', type: 'condition', position: P(360, 320), data: { matchType: 'equals', keyword: 'email_report' } },
      { id: 'api-email', type: 'api', position: P(80, 480), data: postJson('https://example.com/api/clinic/report-email', '{\n  "phone": "{{phone}}",\n  "name": "{{name}}",\n  "action": "email_report"\n}', 'reportEmail') },
      { id: 'send-email-sent', type: 'send', position: P(80, 640), data: sendData({ message: 'Done! Your report has been sent to the email address registered with us. Please check your inbox in a few minutes.', footer: 'Report emailed successfully' }) },
      { id: 'cond-lab', type: 'condition', position: P(360, 480), data: { matchType: 'equals', keyword: 'lab_desk' } },
      { id: 'send-lab-connect', type: 'send', position: P(540, 640), data: sendData({ message: 'Connecting you to the lab desk now. A team member will assist you with the report details and answer any questions.', footer: 'Lab desk support' }) },
      { id: 'handoff-lab', type: 'handoff', position: P(540, 800), data: { reason: 'report_desk_query', note: 'Patient wants to discuss their lab report. Lab team should pull up the result and call if needed.', assignee: 'lab-desk' } },
      { id: 'send-online-info', type: 'send', position: P(900, 640), data: sendData({ message: 'You can view your report anytime by clicking the link we sent. If you have questions about the results, please tap "Talk to lab desk" and a team member will help you.', footer: 'Report available online' }) },
    ],
    edges: [
      edge('trigger-1', 'send-ready'),
      edge('send-ready', 'cond-email'),
      edge('cond-email', 'api-email', 'true'),
      edge('api-email', 'send-email-sent'),
      edge('cond-email', 'cond-lab', 'false'),
      edge('cond-lab', 'send-lab-connect', 'true'),
      edge('send-lab-connect', 'handoff-lab'),
      edge('cond-lab', 'send-online-info', 'false'),
    ],
  },

  {
    id: 'opd-queue-token',
    name: 'OPD Queue & Token',
    industry: 'Clinic / Healthcare',
    description:
      'Issues an OPD token when a patient walks in or messages the number. Sends progressive queue updates at 20 min and 35 min. Pure schedule-based — no AI.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(300, 20), data: { label: 'Patient walks in or messages OPD' } },
      { id: 'cond-opd', type: 'condition', position: P(300, 160), data: { matchType: 'contains', keyword: 'opd' } },
      { id: 'send-token', type: 'send', position: P(80, 340), data: sendData({ sendMode: 'buttons', message: 'Welcome to GrowCare OPD!\n\n🎫 Your token has been generated.\n\nEstimated wait: 25–35 minutes.\nPlease stay nearby and keep your phone handy — we will notify you when it is your turn.', footer: 'OPD Registration Desk', buttons: [{ type: 'quick_reply', label: 'Talk to reception', id: 'reception_help' }, { type: 'quick_reply', label: 'Clinic map', id: 'clinic_map' }] }) },
      { id: 'api-token', type: 'api', position: P(80, 500), data: postJson('https://example.com/api/clinic/opd-tokens', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "registeredAt": "{{timestamp}}"\n}', 'opdToken') },
      { id: 'sched-20min', type: 'schedule', position: P(80, 660), data: { seconds: 1200, message: '⏳ Queue update: You are getting closer! About 10–15 more minutes. Please move to the waiting area outside OPD Room 2 now.' } },
      { id: 'sched-35min', type: 'schedule', position: P(80, 820), data: { seconds: 900, message: '🔔 Your turn is very soon! Please proceed to OPD Counter 2 now and show this message to the nurse. Have your ID and reports ready.' } },
      { id: 'sched-checkin', type: 'schedule', position: P(80, 980), data: { seconds: 600, message: '✅ The doctor is ready for you. Please enter OPD Room 2 when called. If you need help, reply here and reception will assist.' } },
      { id: 'cond-reception', type: 'condition', position: P(80, 1140), data: { matchType: 'equals', keyword: 'reception_help' } },
      { id: 'send-reception', type: 'send', position: P(80, 1300), data: sendData({ message: 'Connecting you to the reception desk. Please wait a moment.', footer: 'Reception support' }) },
      { id: 'handoff-reception', type: 'handoff', position: P(80, 1460), data: { reason: 'opd_reception_help', note: 'OPD patient needs help from reception. Check their queue position and assist.', assignee: 'front-desk' } },
      { id: 'send-not-opd', type: 'send', position: P(560, 340), data: sendData({ sendMode: 'list', message: 'Welcome to GrowCare Clinic! How can we help you today?', footer: 'Choose one option', list: { title: 'Clinic services', buttonText: 'Open menu', sections: [{ title: 'What do you need?', rows: [{ title: 'OPD walk-in', description: 'Get a token for today', rowId: 'opd' }, { title: 'Book appointment', description: 'Schedule a future visit', rowId: 'book_visit' }, { title: 'Lab results', description: 'Check report status', rowId: 'lab_result' }, { title: 'Talk to reception', description: 'Get help from the team', rowId: 'reception_help' }] }] } }) },
    ],
    edges: [
      edge('trigger-1', 'cond-opd'),
      edge('cond-opd', 'send-token', 'true'),
      edge('send-token', 'api-token'),
      edge('api-token', 'sched-20min'),
      edge('sched-20min', 'sched-35min'),
      edge('sched-35min', 'sched-checkin'),
      edge('sched-checkin', 'cond-reception'),
      edge('cond-reception', 'send-reception', 'true'),
      edge('send-reception', 'handoff-reception'),
      edge('cond-opd', 'send-not-opd', 'false'),
    ],
  },

  {
    id: 'vaccination-reminder',
    name: 'Vaccination Due Reminder',
    industry: 'Clinic / Healthcare',
    description:
      'Notifies patients when a vaccination is due. They can book now, get a reminder next week, or mark it as already done. Pure button and condition flow.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(360, 20), data: { label: 'Vaccination due — send reminder to patient' } },
      { id: 'send-vaccine', type: 'send', position: P(360, 160), data: sendData({ sendMode: 'buttons', message: 'Hi! Our records show that your vaccination is due this month. Would you like to get it done at GrowCare Clinic?\n\n💉 Quick, safe, and walk-in friendly.', footer: 'Vaccination reminder', buttons: [{ type: 'quick_reply', label: 'Book now', id: 'vaccine_book' }, { type: 'quick_reply', label: 'Remind me next week', id: 'vaccine_snooze' }, { type: 'quick_reply', label: 'Already done', id: 'vaccine_done' }] }) },
      { id: 'cond-book', type: 'condition', position: P(360, 320), data: { matchType: 'equals', keyword: 'vaccine_book' } },
      { id: 'book-vaccine', type: 'booking', position: P(60, 480), data: { service: 'vaccination', daysAhead: 7, startHour: 9, endHour: 16, intervalMins: 15, reminderHours: 24, message: 'Choose your vaccination slot:', confirmMessage: 'Vaccination slot confirmed for {{slot}}. No fasting required — just bring your previous vaccination card if you have one.' } },
      { id: 'send-vaccine-booked', type: 'send', position: P(60, 660), data: sendData({ message: 'Great! Your vaccination is scheduled for {{slot}}. Please bring your vaccination card or previous records if available.', footer: 'Vaccination confirmed' }) },
      { id: 'cond-snooze', type: 'condition', position: P(360, 480), data: { matchType: 'equals', keyword: 'vaccine_snooze' } },
      { id: 'send-snooze-ack', type: 'send', position: P(380, 660), data: sendData({ message: 'No problem! We will remind you again next week. Please do not delay too long — staying up to date with vaccinations is important.', footer: 'Reminder set for next week' }) },
      { id: 'sched-snooze', type: 'schedule', position: P(380, 820), data: { seconds: 604800, message: 'Vaccination reminder: Last week you asked us to remind you again. Your vaccination is still due. Reply *BOOK* to schedule your slot now.' } },
      { id: 'cond-done', type: 'condition', position: P(360, 660), data: { matchType: 'equals', keyword: 'vaccine_done' } },
      { id: 'set-done', type: 'set', position: P(700, 820), data: { field: 'vaccinationStatus', value: 'self_reported_done' } },
      { id: 'api-done', type: 'api', position: P(700, 980), data: postJson('https://example.com/api/clinic/vaccination-status', '{\n  "phone": "{{phone}}",\n  "name": "{{name}}",\n  "status": "self_reported_done"\n}', 'vaccinationUpdate') },
      { id: 'send-done-ack', type: 'send', position: P(700, 1140), data: sendData({ message: 'Great! We have updated your record. If you have a vaccination certificate, feel free to share it here and we will attach it to your file.', footer: 'Records updated' }) },
    ],
    edges: [
      edge('trigger-1', 'send-vaccine'),
      edge('send-vaccine', 'cond-book'),
      edge('cond-book', 'book-vaccine', 'true'),
      edge('book-vaccine', 'send-vaccine-booked'),
      edge('cond-book', 'cond-snooze', 'false'),
      edge('cond-snooze', 'send-snooze-ack', 'true'),
      edge('send-snooze-ack', 'sched-snooze'),
      edge('cond-snooze', 'cond-done', 'false'),
      edge('cond-done', 'set-done', 'true'),
      edge('set-done', 'api-done'),
      edge('api-done', 'send-done-ack'),
    ],
  },

  // ── AI-ROUTER TEMPLATES ────────────────────────────────────────────────

  {
    id: 'post-visit-follow-up',
    name: 'After Visit Follow-Up',
    industry: 'Clinic / Healthcare',
    description:
      'Handles recovery questions, report sharing, review booking, and urgent follow-up issues.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(420, 20), data: { label: 'Patient replies after a consultation or procedure' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(420, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You help patients after a clinic visit. Send recovery or medicine questions to care guidance. Send serious or worsening symptoms to urgent staff handoff. Send report sharing to upload. Send follow-up visit requests to booking. Use fallback for other questions.',
          confidenceThreshold: 0.56,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Recovery or medicine question', description: 'The patient asks about normal recovery or medicines.' },
            { id: 'route_2', label: 'Worsening symptoms', description: 'The patient says the problem is getting worse.' },
            { id: 'route_3', label: 'Share test results', description: 'The patient wants to send reports for review.' },
            { id: 'route_4', label: 'Book follow-up review', description: 'The patient wants a follow-up visit.' },
            { id: 'fallback', label: 'General questions', description: 'Any normal follow-up question.' },
          ],
        },
      },
      { id: 'send-care', type: 'send', position: P(60, 390), data: sendData({ sendMode: 'buttons', message: 'For routine recovery questions, here are the safest next steps.', footer: 'Post-visit support', buttons: [{ type: 'quick_reply', label: 'Medicine timings', id: 'medicine_help' }, { type: 'quick_reply', label: 'Diet advice', id: 'diet_help' }] }) },
      { id: 'schedule-checkin', type: 'schedule', position: P(60, 550), data: { seconds: 86400, message: 'How are you feeling today? Reply here if pain, swelling, or fever is increasing.' } },
      { id: 'send-warning', type: 'send', position: P(340, 390), data: sendData({ message: 'Your message may need quick clinical review. I am alerting the clinic team now. If you have severe symptoms, please seek urgent care immediately.', footer: 'Urgent follow-up' }) },
      { id: 'handoff-warning', type: 'handoff', position: P(340, 550), data: { reason: 'post_visit_red_flag', note: 'Patient reported worsening symptoms after consultation or procedure. Staff should review urgently.', assignee: 'doctor-assist' } },
      { id: 'send-upload', type: 'send', position: P(620, 390), data: sendData({ sendMode: 'buttons', message: 'Please upload your reports here so the doctor can review them.', footer: 'Report review', buttons: [{ type: 'cta_url', label: 'Upload reports', url: 'https://example.com/follow-up/reports' }, { type: 'quick_reply', label: 'Talk to nurse', id: 'nurse_help' }] }) },
      { id: 'api-upload', type: 'api', position: P(620, 550), data: postJson('https://example.com/api/clinic/post-visit-reports', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "careRoute": "post_visit_report",\n  "message": "{{message}}"\n}', 'postVisitReport') },
      { id: 'book-1', type: 'booking', position: P(900, 390), data: { service: 'follow-up review', daysAhead: 5, startHour: 10, endHour: 18, intervalMins: 20, reminderHours: 24, message: 'Choose a follow-up review slot:', confirmMessage: 'Your follow-up review is confirmed for {{slot}}.' } },
      { id: 'api-review', type: 'api', position: P(900, 550), data: postJson('https://example.com/api/clinic/follow-ups', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "reason": "{{message}}"\n}', 'followUpBooking') },
      { id: 'send-review', type: 'send', position: P(900, 710), data: sendData({ message: 'Booked for {{slot}}. Please bring the latest reports and medicine list for the review.', footer: 'Follow-up booked' }) },
      { id: 'ai-1', type: 'ai', position: P(1180, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a clinic follow-up assistant. Help with simple recovery questions, medicine timing, and review visit prep. Keep answers short. Do not diagnose.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'send-care', 'route_1'),
      edge('send-care', 'schedule-checkin'),
      edge('router-1', 'send-warning', 'route_2'),
      edge('send-warning', 'handoff-warning'),
      edge('router-1', 'send-upload', 'route_3'),
      edge('send-upload', 'api-upload'),
      edge('router-1', 'book-1', 'route_4'),
      edge('book-1', 'api-review'),
      edge('api-review', 'send-review'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
 
 
]

const clone = (value) => JSON.parse(JSON.stringify(value))

export const workflowTemplateList = () =>
  TEMPLATES.map((template) => ({
    id: template.id,
    name: template.name,
    industry: template.industry,
    description: template.description,
    nodes: clone(template.nodes),
    edges: clone(template.edges),
  }))

export const getWorkflowTemplate = (id) =>
  workflowTemplateList().find((template) => template.id === id)
