const P = (x, y) => ({ x, y })

const edge = (source, target, sourceHandle = null) => ({
  id: `edge-${source}-${sourceHandle || 'default'}-${target}-default`,
  source,
  target,
  sourceHandle,
  targetHandle: null,
  animated: true,
})

const sendData = (overrides = {}) => ({
  sendMode: 'text',
  message: '',
  footer: '',
  title: '',
  buttons: [],
  list: null,
  event: null,
  externalAdReply: null,
  template: null,
  product: null,
  carousel: null,
  ...overrides,
})

const postJson = (url, bodyTemplate, saveAs) => ({
  method: 'POST',
  url,
  headers: [{ key: 'Content-Type', value: 'application/json' }],
  bodyTemplate,
  saveAs,
})

const TEMPLATES = [
  {
    id: 'clinic-appointment-intake',
    name: 'Book Visit + Urgent Help',
    industry: 'Clinic / Healthcare',
    description:
      'Books a visit, sends urgent cases to staff, saves the booking, and sends reminders.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(420, 20), data: { label: 'Patient sends a WhatsApp message' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(420, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You work like a clinic front desk. If the patient wants a new appointment, choose booking. If the message sounds urgent or dangerous, choose urgent. If they want to change or cancel a visit, choose reschedule. If they ask about fees or insurance, choose fees. Use fallback for normal clinic questions. Do not diagnose.',
          confidenceThreshold: 0.58,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Book appointment', description: 'The patient wants to book a new visit.' },
            { id: 'route_2', label: 'Urgent symptoms', description: 'The patient says the problem is serious or urgent.' },
            { id: 'route_3', label: 'Reschedule or cancel', description: 'The patient wants to move or cancel a visit.' },
            { id: 'route_4', label: 'Fees or insurance', description: 'The patient asks about cost or insurance.' },
            { id: 'fallback', label: 'General questions', description: 'Normal questions like timing, doctor, location, or reports.' },
          ],
        },
      },
      { id: 'book-1', type: 'booking', position: P(60, 390), data: { service: 'consultation', daysAhead: 7, startHour: 9, endHour: 19, intervalMins: 30, reminderHours: 24, message: 'Choose a consultation slot:', confirmMessage: 'Your visit is reserved for {{slot}}. We will now prepare your intake.' } },
      { id: 'set-1', type: 'set', position: P(60, 550), data: { field: 'careStage', value: 'appointment_booked' } },
      { id: 'api-1', type: 'api', position: P(60, 710), data: postJson('https://example.com/api/clinic/appointments', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "careStage": "{{careStage}}",\n  "lastMessage": "{{message}}"\n}', 'appointment') },
      { id: 'send-confirm', type: 'send', position: P(60, 870), data: sendData({ sendMode: 'buttons', message: 'Booked for {{slot}}. Please bring previous prescriptions, reports, and ID proof.', footer: 'Reply if you need help before the visit', buttons: [{ type: 'quick_reply', label: 'Share symptoms', id: 'share_symptoms' }, { type: 'quick_reply', label: 'Talk to reception', id: 'agent' }] }) },
      { id: 'schedule-1', type: 'schedule', position: P(60, 1030), data: { seconds: 86400, message: 'Reminder: your appointment is tomorrow at {{slot}}. Please arrive 10 minutes early.' } },
      { id: 'schedule-2', type: 'schedule', position: P(60, 1190), data: { seconds: 10800, message: 'Before your visit, keep your reports ready and avoid missing the slot. Reply here if you need to reschedule.' } },
      { id: 'send-urgent', type: 'send', position: P(340, 390), data: sendData({ message: 'Your message sounds urgent. I am connecting you to the clinic team right away. If this is a medical emergency, please call emergency services immediately.', footer: 'Urgent support' }) },
      { id: 'handoff-urgent', type: 'handoff', position: P(340, 550), data: { reason: 'urgent_triage', note: 'Possible urgent symptoms. Staff should review this chat immediately and call the patient if needed.', assignee: 'triage-desk' } },
      { id: 'send-reschedule', type: 'send', position: P(620, 390), data: sendData({ sendMode: 'buttons', message: 'I can help the reception team reschedule or cancel your visit.', footer: 'Choose one option', buttons: [{ type: 'quick_reply', label: 'Reschedule', id: 'reschedule' }, { type: 'quick_reply', label: 'Cancel visit', id: 'cancel_visit' }] }) },
      { id: 'handoff-reschedule', type: 'handoff', position: P(620, 550), data: { reason: 'reschedule_request', note: 'Patient wants to change or cancel an existing booking. Staff should verify slot and update the booking.', assignee: 'front-desk' } },
      { id: 'send-fees', type: 'send', position: P(900, 390), data: sendData({ sendMode: 'buttons', message: 'Here are the quickest next steps for fee and insurance questions.', footer: 'Choose one option', buttons: [{ type: 'cta_url', label: 'View consultation fees', url: 'https://example.com/fees' }, { type: 'quick_reply', label: 'Talk to billing', id: 'billing_help' }] }) },
      { id: 'ai-1', type: 'ai', position: P(1180, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a clinic WhatsApp assistant. Help with clinic timings, visit prep, doctor availability, and what documents to bring. Keep replies short and simple. Do not diagnose.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'book-1', 'route_1'),
      edge('book-1', 'set-1'),
      edge('set-1', 'api-1'),
      edge('api-1', 'send-confirm'),
      edge('send-confirm', 'schedule-1'),
      edge('schedule-1', 'schedule-2'),
      edge('router-1', 'send-urgent', 'route_2'),
      edge('send-urgent', 'handoff-urgent'),
      edge('router-1', 'send-reschedule', 'route_3'),
      edge('send-reschedule', 'handoff-reschedule'),
      edge('router-1', 'send-fees', 'route_4'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  {
    id: 'clinic-smart-front-desk',
    name: 'Smart Front Desk',
    industry: 'Clinic / Healthcare',
    description:
      'Sorts messages into booking, billing, department help, staff support, or general questions.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(380, 20), data: { label: 'Patient message reaches the clinic inbox' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(380, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You are a clinic receptionist. Send booking requests to appointments. Send fee or insurance questions to billing. Send department or service questions to the options menu. Send complaints or staff requests to human handoff. Use fallback for normal questions.',
          confidenceThreshold: 0.58,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Fees and billing', description: 'Cost, estimate, insurance, or receipt question.' },
            { id: 'route_2', label: 'Appointment booking', description: 'The patient wants to book or confirm a slot.' },
            { id: 'route_3', label: 'Departments and services', description: 'The patient wants help choosing a doctor or service.' },
            { id: 'route_4', label: 'Reception handoff', description: 'The patient wants a real person or has a complaint.' },
            { id: 'fallback', label: 'General questions', description: 'Any normal clinic question.' },
          ],
        },
      },
      { id: 'send-fees', type: 'send', position: P(40, 390), data: sendData({ sendMode: 'buttons', message: 'Here are the quickest ways to handle fees and billing.', footer: 'Billing desk support', buttons: [{ type: 'cta_url', label: 'View fees', url: 'https://example.com/fees' }, { type: 'quick_reply', label: 'Insurance help', id: 'insurance_help' }] }) },
      { id: 'book-1', type: 'booking', position: P(300, 390), data: { service: 'consultation', daysAhead: 5, startHour: 10, endHour: 18, intervalMins: 30, reminderHours: 24, message: 'Pick a consultation time:', confirmMessage: 'Your consultation is confirmed for {{slot}}.' } },
      { id: 'api-1', type: 'api', position: P(300, 550), data: postJson('https://example.com/api/clinic/front-desk-bookings', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "route": "{{router.label}}"\n}', 'frontDeskBooking') },
      { id: 'send-booked', type: 'send', position: P(300, 710), data: sendData({ message: 'Your consultation is booked for {{slot}}. Reply here anytime if you need help before the visit.', footer: 'GrowCare Clinic' }) },
      { id: 'send-menu', type: 'send', position: P(580, 390), data: sendData({ sendMode: 'list', message: 'Choose the department or help area you need.', footer: 'Select one option', list: { title: 'Clinic options', buttonText: 'Open options', sections: [{ title: 'Popular paths', rows: [{ title: 'General medicine', description: 'Routine visit, fever, pain, follow-up', rowId: 'general_medicine' }, { title: 'Diagnostics and reports', description: 'Book tests or ask about results', rowId: 'diagnostics' }, { title: 'Billing and insurance', description: 'Fees, bills, and receipts', rowId: 'billing' }] }] } }) },
      { id: 'send-agent', type: 'send', position: P(860, 390), data: sendData({ message: 'I am connecting you to the clinic team now.', footer: 'Human support' }) },
      { id: 'handoff-1', type: 'handoff', position: P(860, 550), data: { reason: 'front_desk_escalation', note: 'Patient requested human support or raised a complaint. Reception should review the full chat.', assignee: 'front-desk' } },
      { id: 'ai-1', type: 'ai', position: P(1140, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a clinic WhatsApp assistant. Answer simple questions about timing, doctors, reports, location, and visit prep. Keep answers short. Do not diagnose.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'send-fees', 'route_1'),
      edge('router-1', 'book-1', 'route_2'),
      edge('book-1', 'api-1'),
      edge('api-1', 'send-booked'),
      edge('router-1', 'send-menu', 'route_3'),
      edge('router-1', 'send-agent', 'route_4'),
      edge('send-agent', 'handoff-1'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  {
    id: 'diagnostics-report-desk',
    name: 'Tests + Reports Desk',
    industry: 'Clinic / Healthcare',
    description:
      'Helps patients upload reports, book tests, check report status, or talk to the lab desk.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(400, 20), data: { label: 'Patient asks about tests, scans, or reports' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(400, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You help with clinic tests and reports. Send upload requests to the upload path. Send test booking requests to booking. Send report status questions to report help. Send staff requests to human handoff. Use fallback for other questions.',
          confidenceThreshold: 0.56,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Upload reports', description: 'The patient wants to send reports or prescriptions.' },
            { id: 'route_2', label: 'Book diagnostic slot', description: 'The patient wants to book a test or scan.' },
            { id: 'route_3', label: 'Result status', description: 'The patient wants to know if the report is ready.' },
            { id: 'route_4', label: 'Lab desk handoff', description: 'The patient wants a person or has a report issue.' },
            { id: 'fallback', label: 'General questions', description: 'Any normal test or report question.' },
          ],
        },
      },
      { id: 'send-upload', type: 'send', position: P(40, 390), data: sendData({ sendMode: 'buttons', message: 'You can upload prescriptions or old reports before the visit.', footer: 'Document collection', buttons: [{ type: 'cta_url', label: 'Upload reports', url: 'https://example.com/reports/upload' }, { type: 'quick_reply', label: 'Need help', id: 'report_help' }] }) },
      { id: 'api-upload', type: 'api', position: P(40, 550), data: postJson('https://example.com/api/clinic/report-uploads', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "requestType": "report_upload",\n  "message": "{{message}}"\n}', 'reportUpload') },
      { id: 'schedule-upload', type: 'schedule', position: P(40, 710), data: { seconds: 21600, message: 'Friendly reminder: please upload the requested reports before your diagnostic visit.' } },
      { id: 'book-1', type: 'booking', position: P(320, 390), data: { service: 'diagnostic slot', daysAhead: 6, startHour: 8, endHour: 18, intervalMins: 30, reminderHours: 24, message: 'Choose a time for your diagnostic slot:', confirmMessage: 'Your diagnostic slot is booked for {{slot}}.' } },
      { id: 'api-booking', type: 'api', position: P(320, 550), data: postJson('https://example.com/api/clinic/diagnostics-bookings', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "testRequest": "{{message}}"\n}', 'diagnosticBooking') },
      { id: 'send-booked', type: 'send', position: P(320, 710), data: sendData({ message: 'Booked for {{slot}}. Please carry your doctor note, previous results, and fasting instructions if applicable.', footer: 'Diagnostics desk' }) },
      { id: 'send-results', type: 'send', position: P(640, 390), data: sendData({ sendMode: 'list', message: 'Choose the report support option you need.', footer: 'Select one option', list: { title: 'Report options', buttonText: 'Open options', sections: [{ title: 'Diagnostics support', rows: [{ title: 'Report ready status', description: 'Check if your report is ready', rowId: 'report_ready' }, { title: 'Email me the report', description: 'Request a digital copy', rowId: 'email_report' }, { title: 'Talk to lab desk', description: 'Get manual help from the team', rowId: 'lab_support' }] }] } }) },
      { id: 'send-agent', type: 'send', position: P(920, 390), data: sendData({ message: 'I am connecting you to the diagnostics desk now.', footer: 'Human support' }) },
      { id: 'handoff-1', type: 'handoff', position: P(920, 550), data: { reason: 'diagnostics_support', note: 'Patient needs report or diagnostics coordination from a staff member.', assignee: 'lab-desk' } },
      { id: 'ai-1', type: 'ai', position: P(1200, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a diagnostics desk assistant. Help with fasting rules, report timing, sample collection time, and what to bring. Do not explain medical results.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'send-upload', 'route_1'),
      edge('send-upload', 'api-upload'),
      edge('api-upload', 'schedule-upload'),
      edge('router-1', 'book-1', 'route_2'),
      edge('book-1', 'api-booking'),
      edge('api-booking', 'send-booked'),
      edge('router-1', 'send-results', 'route_3'),
      edge('router-1', 'send-agent', 'route_4'),
      edge('send-agent', 'handoff-1'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  {
    id: 'post-visit-follow-up',
    name: 'After Visit Follow-Up',
    industry: 'Clinic / Healthcare',
    description:
      'Handles recovery questions, report sharing, review booking, and urgent follow-up issues.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(420, 20), data: { label: 'Patient replies after a consultation or procedure' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(420, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You help patients after a clinic visit. Send recovery or medicine questions to care guidance. Send serious or worsening symptoms to urgent staff handoff. Send report sharing to upload. Send follow-up visit requests to booking. Use fallback for other questions.',
          confidenceThreshold: 0.56,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Recovery or medicine question', description: 'The patient asks about normal recovery or medicines.' },
            { id: 'route_2', label: 'Worsening symptoms', description: 'The patient says the problem is getting worse.' },
            { id: 'route_3', label: 'Share test results', description: 'The patient wants to send reports for review.' },
            { id: 'route_4', label: 'Book follow-up review', description: 'The patient wants a follow-up visit.' },
            { id: 'fallback', label: 'General questions', description: 'Any normal follow-up question.' },
          ],
        },
      },
      { id: 'send-care', type: 'send', position: P(60, 390), data: sendData({ sendMode: 'buttons', message: 'For routine recovery questions, here are the safest next steps.', footer: 'Post-visit support', buttons: [{ type: 'quick_reply', label: 'Medicine timings', id: 'medicine_help' }, { type: 'quick_reply', label: 'Diet advice', id: 'diet_help' }] }) },
      { id: 'schedule-checkin', type: 'schedule', position: P(60, 550), data: { seconds: 86400, message: 'How are you feeling today? Reply here if pain, swelling, or fever is increasing.' } },
      { id: 'send-warning', type: 'send', position: P(340, 390), data: sendData({ message: 'Your message may need quick clinical review. I am alerting the clinic team now. If you have severe symptoms, please seek urgent care immediately.', footer: 'Urgent follow-up' }) },
      { id: 'handoff-warning', type: 'handoff', position: P(340, 550), data: { reason: 'post_visit_red_flag', note: 'Patient reported worsening symptoms after consultation or procedure. Staff should review urgently.', assignee: 'doctor-assist' } },
      { id: 'send-upload', type: 'send', position: P(620, 390), data: sendData({ sendMode: 'buttons', message: 'Please upload your reports here so the doctor can review them.', footer: 'Report review', buttons: [{ type: 'cta_url', label: 'Upload reports', url: 'https://example.com/follow-up/reports' }, { type: 'quick_reply', label: 'Talk to nurse', id: 'nurse_help' }] }) },
      { id: 'api-upload', type: 'api', position: P(620, 550), data: postJson('https://example.com/api/clinic/post-visit-reports', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "careRoute": "post_visit_report",\n  "message": "{{message}}"\n}', 'postVisitReport') },
      { id: 'book-1', type: 'booking', position: P(900, 390), data: { service: 'follow-up review', daysAhead: 5, startHour: 10, endHour: 18, intervalMins: 20, reminderHours: 24, message: 'Choose a follow-up review slot:', confirmMessage: 'Your follow-up review is confirmed for {{slot}}.' } },
      { id: 'api-review', type: 'api', position: P(900, 550), data: postJson('https://example.com/api/clinic/follow-ups', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "reason": "{{message}}"\n}', 'followUpBooking') },
      { id: 'send-review', type: 'send', position: P(900, 710), data: sendData({ message: 'Booked for {{slot}}. Please bring the latest reports and medicine list for the review.', footer: 'Follow-up booked' }) },
      { id: 'ai-1', type: 'ai', position: P(1180, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a clinic follow-up assistant. Help with simple recovery questions, medicine timing, and review visit prep. Keep answers short. Do not diagnose.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'send-care', 'route_1'),
      edge('send-care', 'schedule-checkin'),
      edge('router-1', 'send-warning', 'route_2'),
      edge('send-warning', 'handoff-warning'),
      edge('router-1', 'send-upload', 'route_3'),
      edge('send-upload', 'api-upload'),
      edge('router-1', 'book-1', 'route_4'),
      edge('book-1', 'api-review'),
      edge('api-review', 'send-review'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  {
    id: 'chronic-care-recall',
    name: 'Review + Refill Care Flow',
    industry: 'Clinic / Healthcare',
    description:
      'Books review visits, collects home readings, handles refill requests, and sends nurse support.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(420, 20), data: { label: 'Patient replies to a chronic care reminder or sends a review request' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(420, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You help patients with long-term care. Send review visit requests to booking. Send refill requests to refill processing. Send home readings to the vitals path. Send nurse or doctor help requests to human handoff. Use fallback for other questions.',
          confidenceThreshold: 0.56,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Book chronic care review', description: 'The patient wants a review for a long-term condition.' },
            { id: 'route_2', label: 'Prescription refill', description: 'The patient wants a refill.' },
            { id: 'route_3', label: 'Share vitals', description: 'The patient wants to share BP, sugar, weight, or other readings.' },
            { id: 'route_4', label: 'Nurse or doctor help', description: 'The patient wants a person or extra support.' },
            { id: 'fallback', label: 'General questions', description: 'Any normal long-term care question.' },
          ],
        },
      },
      { id: 'book-1', type: 'booking', position: P(60, 390), data: { service: 'chronic care review', daysAhead: 10, startHour: 9, endHour: 18, intervalMins: 20, reminderHours: 24, message: 'Choose a review slot:', confirmMessage: 'Your chronic care review is confirmed for {{slot}}.' } },
      { id: 'api-review', type: 'api', position: P(60, 550), data: postJson('https://example.com/api/clinic/chronic-care-reviews', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "slot": "{{slot}}",\n  "program": "chronic_care_review"\n}', 'chronicReview') },
      { id: 'send-booked', type: 'send', position: P(60, 710), data: sendData({ message: 'Booked for {{slot}}. Please carry your latest readings, reports, and current medicines.', footer: 'Review scheduled' }) },
      { id: 'schedule-review', type: 'schedule', position: P(60, 870), data: { seconds: 86400, message: 'Reminder: please keep BP, sugar, weight, or other home readings ready before the review.' } },
      { id: 'api-refill', type: 'api', position: P(340, 390), data: postJson('https://example.com/api/clinic/refill-requests', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "request": "{{message}}"\n}', 'refillRequest') },
      { id: 'send-refill', type: 'send', position: P(340, 550), data: sendData({ message: 'Your refill request has been sent to the clinic. A staff member will verify it before issuing a repeat prescription.', footer: 'Refill request received' }) },
      { id: 'handoff-refill', type: 'handoff', position: P(340, 710), data: { reason: 'refill_verification', note: 'Patient requested prescription refill. Staff should verify medication and follow-up needs.', assignee: 'nurse-desk' } },
      { id: 'send-vitals', type: 'send', position: P(620, 390), data: sendData({ sendMode: 'buttons', message: 'Please share your latest home readings so the care team can review them.', footer: 'Monitoring support', buttons: [{ type: 'cta_url', label: 'Upload readings', url: 'https://example.com/vitals' }, { type: 'quick_reply', label: 'Need help', id: 'vitals_help' }] }) },
      { id: 'api-vitals', type: 'api', position: P(620, 550), data: postJson('https://example.com/api/clinic/vitals', '{\n  "name": "{{name}}",\n  "phone": "{{phone}}",\n  "source": "whatsapp",\n  "message": "{{message}}"\n}', 'vitals') },
      { id: 'schedule-vitals', type: 'schedule', position: P(620, 710), data: { seconds: 43200, message: 'Reminder: if possible, share today\'s BP, sugar, or weight readings so the doctor can review trends.' } },
      { id: 'send-nurse', type: 'send', position: P(900, 390), data: sendData({ message: 'I am connecting you to the nurse or clinic team for more detailed support.', footer: 'Human support' }) },
      { id: 'handoff-nurse', type: 'handoff', position: P(900, 550), data: { reason: 'chronic_care_support', note: 'Patient needs chronic-care support from nurse or doctor team.', assignee: 'nurse-desk' } },
      { id: 'ai-1', type: 'ai', position: P(1180, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a chronic care support assistant. Help patients get ready for review visits and know what readings to share. Keep answers simple. Do not change treatment or diagnose.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'book-1', 'route_1'),
      edge('book-1', 'api-review'),
      edge('api-review', 'send-booked'),
      edge('send-booked', 'schedule-review'),
      edge('router-1', 'api-refill', 'route_2'),
      edge('api-refill', 'send-refill'),
      edge('send-refill', 'handoff-refill'),
      edge('router-1', 'send-vitals', 'route_3'),
      edge('send-vitals', 'api-vitals'),
      edge('api-vitals', 'schedule-vitals'),
      edge('router-1', 'send-nurse', 'route_4'),
      edge('send-nurse', 'handoff-nurse'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
  {
    id: 'procedure-prep-and-clearance',
    name: 'Procedure Prep + Safety Check',
    industry: 'Clinic / Healthcare',
    description:
      'Sends procedure prep steps, payment help, reschedule support, and urgent safety handoff.',
    nodes: [
      { id: 'trigger-1', type: 'trigger', position: P(420, 20), data: { label: 'Patient asks about a booked procedure or planned surgery' } },
      {
        id: 'router-1',
        type: 'router',
        position: P(420, 170),
        data: {
          provider: 'openai',
          model: 'gpt-4o-mini',
          systemPrompt:
            'You help patients before a procedure. Send prep and fasting questions to the prep path. Send payment or estimate questions to billing. Send safety concerns to urgent handoff. Send reschedule questions to front-desk handoff. Use fallback for other questions.',
          confidenceThreshold: 0.58,
          fallbackRoute: 'fallback',
          saveAs: 'router',
          routes: [
            { id: 'route_1', label: 'Preparation checklist', description: 'The patient asks how to get ready for the procedure.' },
            { id: 'route_2', label: 'Estimate or payment', description: 'The patient asks about cost or payment.' },
            { id: 'route_3', label: 'Safety concern', description: 'The patient reports a problem that may make the procedure unsafe.' },
            { id: 'route_4', label: 'Reschedule procedure', description: 'The patient wants to move or cancel the procedure.' },
            { id: 'fallback', label: 'General questions', description: 'Any normal procedure question.' },
          ],
        },
      },
      { id: 'send-prep', type: 'send', position: P(60, 390), data: sendData({ sendMode: 'list', message: 'Here is the pre-procedure checklist.', footer: 'Review carefully', list: { title: 'Procedure prep', buttonText: 'Open checklist', sections: [{ title: 'Before arrival', rows: [{ title: 'Fasting rules', description: 'Check when to stop food and liquids', rowId: 'fasting_rules' }, { title: 'Medicines to discuss', description: 'Blood thinners, diabetes medicines, and regular tablets', rowId: 'medicines_review' }, { title: 'What to bring', description: 'ID, reports, consent forms, and previous prescriptions', rowId: 'what_to_bring' }] }] } }) },
      { id: 'schedule-prep', type: 'schedule', position: P(60, 550), data: { seconds: 43200, message: 'Reminder: review the fasting checklist and keep all reports ready before the procedure.' } },
      { id: 'payment-1', type: 'payment', position: P(340, 390), data: { message: 'Use the secure link below for your estimate or advance payment.', label: 'Open payment link', linkTemplate: 'https://example.com/payments/procedure?phone={{phone}}', amount: '', currency: 'INR ' } },
      { id: 'schedule-payment', type: 'schedule', position: P(340, 550), data: { seconds: 86400, message: 'Reminder: please complete the pending estimate or advance payment if requested by the clinic.' } },
      { id: 'send-redflag', type: 'send', position: P(620, 390), data: sendData({ message: 'Your message may affect procedure safety. I am alerting the clinic team now so they can guide you.', footer: 'Urgent review' }) },
      { id: 'handoff-redflag', type: 'handoff', position: P(620, 550), data: { reason: 'procedure_red_flag', note: 'Patient reported safety concern before procedure. Team should review urgently before proceeding.', assignee: 'procedure-desk' } },
      { id: 'send-reschedule', type: 'send', position: P(900, 390), data: sendData({ message: 'I am forwarding your reschedule request to the clinic team now.', footer: 'Front desk support' }) },
      { id: 'handoff-reschedule', type: 'handoff', position: P(900, 550), data: { reason: 'procedure_reschedule', note: 'Patient wants to move or cancel procedure date. Staff should update slot and instructions.', assignee: 'front-desk' } },
      { id: 'ai-1', type: 'ai', position: P(1180, 390), data: { provider: 'openai', model: 'gpt-4o-mini', systemPrompt: 'You are a procedure support assistant. Help with timing, prep steps, fasting, documents, and arrival details. Keep answers simple. Do not give medical clearance.' } },
    ],
    edges: [
      edge('trigger-1', 'router-1'),
      edge('router-1', 'send-prep', 'route_1'),
      edge('send-prep', 'schedule-prep'),
      edge('router-1', 'payment-1', 'route_2'),
      edge('payment-1', 'schedule-payment'),
      edge('router-1', 'send-redflag', 'route_3'),
      edge('send-redflag', 'handoff-redflag'),
      edge('router-1', 'send-reschedule', 'route_4'),
      edge('send-reschedule', 'handoff-reschedule'),
      edge('router-1', 'ai-1', 'fallback'),
    ],
  },
]

const clone = (value) => JSON.parse(JSON.stringify(value))

export const workflowTemplateList = () =>
  TEMPLATES.map((template) => ({
    id: template.id,
    name: template.name,
    industry: template.industry,
    description: template.description,
    nodes: clone(template.nodes),
    edges: clone(template.edges),
  }))

export const getWorkflowTemplate = (id) =>
  workflowTemplateList().find((template) => template.id === id)
