// Atoms barrel — import any atom from a single path:
//   import { Button, Input, Card } from '@/components/atoms'
export { default as Button } from './Button'
export { default as Input } from './Input'
export { default as Label } from './Label'
export { default as Card } from './Card'
export { default as Badge } from './Badge'
export { default as Table } from './Table'
export { default as Alert } from './Alert'
export { default as Spinner } from './Spinner'
export { default as Logo } from './Logo'
export { default as Modal } from './Modal'
